### ISSUE TITLE
[APP] AZURE SQL Server 

### ISSUE THREAD

**Issue by TheZapotech** [PipedreamHQ/pipedream#7377] opened 2023-07-25 15:48 UTC
**Name of app / service**
Azure SQL Server

**Link to developer documentation**
azure.microsoft.com :-)

**Is lack of support preventing you from building workflows, or do you have a workaround?**
I will not adopt it unless you will deploy this feature 

**Triggers**
New or Updated Row
New Row

**Heads up by Sergio**
This issue can be marked as closed if the Microsoft SQL Server implementation of #6408 covers that app's database engine service, because Microsoft SQL Server has support to access Azure SQL Database, and source implementation are expected to be implmented in a similar way to PostgreSQL, which is a different database engine. That said, when it comes to the Microsoft SQL Server issue, the API documention shown is for the reporting services engine.

Microsoft SQL Server app addressing the database engine was submitted for approval at https://pipedream.com/admin/apps/microsoft_sql_server

**Comment by sergio-eliot-rodriguez** [comment] 2023-07-26 04:10
Hey @TheZapotech that's pretty awesome!
Great app request, I appreciate it - I'm a SQL Server user myself.

So, I'm collaborating with Pipedream creating new app integrations.
Here I wanted yo ask you on where do you want to use Azure SQL Server the most?

do you want to run queries via Pipedream against your database?
i.e similar like this sample request we have for MySQL: https://pipedream.com/apps/mysql?
![image](https://github.com/PipedreamHQ/pipedream/assets/101526248/72ec26df-15f3-4914-a941-03284f0e0c9e)

or do you want to access other SQL Server features via a REST API (which Pipedream is used for extensively, to hit REST APIs), like this one for SQL Server's Reporting Services (or Analysis Services, and so on)? 
Here is Reporting Services APIs:
https://learn.microsoft.com/en-us/sql/reporting-services/developer/rest-api?view=sql-server-ver16

So, if you allow me the question, specifically which service, within Azure SQL Server do you want to connect to?

I need to ask because we need to narrow down your request. SQL Server is an enormous product, and we may need to create several apps integrations on Pipedream, depending on the use case.

Let us know please thanks!

Sergio

**Comment by TheZapotech** [comment] 2023-07-26 06:24
Hello Sergio,
                my need would be to have New Row or Single Field Update triggers (Also both like Pipedream allows for Postgre) and possibly the opportunity to run queries during the workflow.
                With this 3 things Pipedream can be really effective to me.

Thank you

From: sergio-eliot-rodriguez ***@***.***>
Date: Wednesday, 26 July 2023 at 06:11
To: PipedreamHQ/pipedream ***@***.***>
Cc: TheZapotech ***@***.***>, Mention ***@***.***>
Subject: Re: [PipedreamHQ/pipedream] [APP] AZURE SQL Server (Issue #7377)

Hey @TheZapotech<https://github.com/TheZapotech> that's pretty awesome!
Great app request, I appreciate it - I'm a SQL Server user myself.

So, I'm collaborating with Pipedream creating new app integrations.
Here I wanted yo ask you on where do you want to use Azure SQL Server the most?

do you want to run queries via Pipedream against your database?
i.e similar like this sample request we have for MySQL: https://pipedream.com/apps/mysql?
[image]<https://user-images.githubusercontent.com/101526248/256113804-72ec26df-15f3-4914-a941-03284f0e0c9e.png>

or do you want to access other SQL Server features via a REST API (which Pipedream is used for extensively, to hit REST APIs), like this one for SQL Server's Reporting Services (or Analysis Services, and so on)?
Here is Reporting Services APIs:
https://learn.microsoft.com/en-us/sql/reporting-services/developer/rest-api?view=sql-server-ver16

So, if you allow me the question, specifically which service, within Azure SQL Server do you want to connect to?

I need to ask because we need to narrow down your request. SQL Server is an enormous product, and we may need to create several apps integrations on Pipedream, depending on the use case.

Let us know please thanks!

Sergio

**Comment by dylburger** [comment] 2023-08-02 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by sergio-eliot-rodriguez** [comment] 2023-08-03 10:41
Hello @TheZapotech ,

Thanks for the response, that's helpful to approach the integration.

So, effectively, everything you need can be done using a database engine for Azure SQL Server.
I confirmed looking at Postgres implementation, built triggers query the database for check for new rows or changes in fields.

**Comment by dylburger** [comment] 2023-08-10 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Comment by malexanderlim** [comment] 2023-10-05 16:06
Hi @TheZapotech , our integration to Microsoft SQL Server is complete - can you please give this a try and let us know if this works for your use case?

https://pipedream.com/apps/microsoft-sql-server#popular-microsoft-sql-server-triggers

**Comment by sergio-eliot-rodriguez** [comment] 2024-03-04 16:07
Closing this issue to clean space in App & integrations GitHub project

**Closed by sergio-eliot-rodriguez** 2024-03-04 16:07 UTC
Labels: enhancement, app, triaged
