### ISSUE TITLE
[APP]Tradeovate (Futures Trading App)

### ISSUE THREAD

**Issue by MongoSan** [PipedreamHQ/pipedream#5348] opened 2023-01-28 22:58 UTC
TradoVate

https://api.tradovate.com/  & https://github.com/tradovate/example-api-oauth

I would like to get the OAuth Setup as a connected account so that I can easily use it in workflow steps

Thanks !
Tom

**Comment by sergio-eliot-rodriguez** [comment] 2024-06-17 17:25
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/4747

**Closed by sergio-eliot-rodriguez** 2024-06-17 17:25 UTC
Labels: enhancement, app, triaged, OAuth, added to app backlog
