### ISSUE TITLE
[Components] fractel

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11891] opened 2024-05-08 23:33 UTC
# fractel
## URLs
- https://developer.fonestorm.com/reference/authorization
#### Prompt
Emit new event when a call is received. Props: Phone Number (required), Call Duration (optional)
#### URLs
- https://developer.fonestorm.com/reference/calls
- https://developer.fonestorm.com/reference/sendcall
- https://developer.fonestorm.com/reference/set-cdr-callback
#### Prompt
Emit new event when a new SMS or MMS is received. Props: Phone Number (required), Message Content (required)
#### URLs
- https://developer.fonestorm.com/reference/messages
- https://developer.fonestorm.com/reference/sendmessage
- https://developer.fonestorm.com/reference/number-lookups
- https://developer.fonestorm.com/reference/lookupnumbers
#### Prompt
Initiates a new call to a specified phone number. Required prop is 'phone number'.
#### URLs
- https://developer.fonestorm.com/reference/calls
- https://developer.fonestorm.com/reference/sendcall
#### Prompt
Sends an SMS or MMS to a specified phone number. Required props are 'phone number' and 'message'. Optional prop could be 'media' for MMS.
#### URLs
- https://developer.fonestorm.com/reference/messages
- https://developer.fonestorm.com/reference/sendmessage
- https://developer.fonestorm.com/reference/message-object

**Comment by michelle0927** [comment] 2024-05-16 19:09
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/11791

**Closed by michelle0927** 2024-05-16 19:09 UTC
Labels: triaged
