### ISSUE TITLE
[ACTION] Sendgrid: Send Email action should support attachments

### ISSUE THREAD

**Issue by dylburger** [PipedreamHQ/pipedream#1129] opened 2021-03-29 18:55 UTC

**Comment by dylburger** [comment] 2021-04-22 22:19
We should create a component action for sending email using Sendgrid, and add support for this when we do.

**Comment by dannyroosevelt** [comment] 2021-11-23 19:05
@sergioeliot2039 does the "Send Email" action in https://github.com/PipedreamHQ/pipedream/pull/1288 support attachments? If so we can probably close this issue since it's mostly a duplicate of https://github.com/PipedreamHQ/pipedream/issues/1248

**Comment by sergioeliot2039** [comment] 2022-02-23 18:42
Yes , it does.
I am closing this issue now.

**Closed by sergioeliot2039** 2022-02-23 18:42 UTC
Labels: action
