### ISSUE TITLE
[APP] LinkedIn Lead Gen ads

### ISSUE THREAD

**Issue by todsac** [PipedreamHQ/pipedream#568] opened 2020-10-23 19:32 UTC
**Name of app / service**
LinkedIn Lead Gen ads

**Link to developer documentation**

**Is lack of support preventing you from building workflows, or do you have a workaround?**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by dylburger** [comment] 2021-04-22 22:48
Duplicate of #932 , tracking there.

**Closed by dylburger** 2021-04-22 22:48 UTC
Labels: app, enhancement
