### ISSUE TITLE
[Components] hypeauditor

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12681] opened 2024-07-01 23:30 UTC
# hypeauditor
## URLs
- https://hypeauditor.readme.io/reference/basic
#### Prompt
Finds the profile of an influencer across all supported social networks. Requires the 'username' prop to specify the influencer.
#### URLs
- https://hypeauditor.readme.io/reference/report_instagram
- https://hypeauditor.readme.io/reference/get_report_ig_username
- https://hypeauditor.readme.io/reference/report_youtube
- https://hypeauditor.readme.io/reference/get_report_youtube
- https://hypeauditor.readme.io/reference/report_tiktok
- https://hypeauditor.readme.io/reference/get_report_tiktok
- https://hypeauditor.readme.io/reference/report_twitch
- https://hypeauditor.readme.io/reference/get_report_twitch
- https://hypeauditor.readme.io/reference/report_twitter
- https://hypeauditor.readme.io/reference/get_report_twitter
- https://hypeauditor.readme.io/reference/report_snapchat
- https://hypeauditor.readme.io/reference/get_report_snapchat
#### Prompt
Retrieves a comprehensive report of a specific TikTok user. The 'username' prop is required to specify the TikTok handle.
#### URLs
- https://hypeauditor.readme.io/reference/report_tiktok
- https://hypeauditor.readme.io/reference/get_report_tiktok
- https://hypeauditor.readme.io/reference/account_media_tiktok
- https://hypeauditor.readme.io/reference/get_media_tt
- https://hypeauditor.readme.io/reference/metrics_history_tiktok
- https://hypeauditor.readme.io/reference/get_history_tt
- https://hypeauditor.readme.io/reference/brands_mentions_tiktok
- https://hypeauditor.readme.io/reference/get_mentions_tt
- https://hypeauditor.readme.io/reference/example_tiktok
#### Prompt
Generates a detailed report for a specific Youtube channel. The 'channelId' prop is necessary to specify the channel.
#### URLs
- https://hypeauditor.readme.io/reference/report_youtube
- https://hypeauditor.readme.io/reference/get_report_youtube
- https://hypeauditor.readme.io/reference/account_media_youtube
- https://hypeauditor.readme.io/reference/get_media_yt
- https://hypeauditor.readme.io/reference/brands_mentions_youtube
- https://hypeauditor.readme.io/reference/get_mentions_yt

**Comment by malexanderlim** [comment] 2024-07-02 22:27
Need account with API access

**Comment by michelle0927** [comment] 2024-12-14 22:19
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/13275

**Closed by michelle0927** 2024-12-14 22:19 UTC
Labels: triaged
