### ISSUE TITLE
[BUG] Raindrop.io component does not discover new events

### ISSUE THREAD

**Issue by selfagency** [PipedreamHQ/pipedream#5496] opened 2023-02-15 18:50 UTC
**Describe the bug**
Raindrop.io integration does not find new events

**To Reproduce**
1. Add a Raindrop.io account
2. Go to Workflows > New
3. Select Raindop/New Bookmark as a trigger
4. Add a new bookmark with Raindrop.io
5. Click 'Try now'
6. Get no new events

**Expected behavior**
For new bookmarks to trigger an event

**Comment by vunguyenhung** [comment] 2023-02-17 01:22
Hello @selfagency,

I couldn't reproduce your issue as I added bookmarks on Raindrop.io and see the new events emitted
![image](https://user-images.githubusercontent.com/18277920/219524362-f89973ae-a966-44de-80bf-678c31537106.png)
![image](https://user-images.githubusercontent.com/18277920/219524338-688a92f4-0ba8-4ad2-bcb6-5dbb67d29638.png)

Would you mind sharing the source logs 
![image](https://user-images.githubusercontent.com/18277920/219524858-685a43b5-3732-4ac3-8fdf-b2b08b301607.png)

**Comment by dylburger** [comment] 2023-02-24 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2023-02-24 23:29 UTC
Labels: bug, question
