### ISSUE TITLE
[APP] SeaTable

### ISSUE THREAD

**Issue by christophdb** [PipedreamHQ/pipedream#7203] opened 2023-07-10 12:17 UTC
**Name of app / service**: SeaTable, world leading self-hosted no-code platform.

**Link to developer documentation**: https://api.seatable.io. 

**Is lack of support preventing you from building workflows, or do you have a workaround?**: SeaTable is an alternative to Airtable, which is quite expensive and only available as SaaS solution. There are multiple countries where laws can prevent the usage of Airtable because data is transferred to the US. This is valid for the public sector of Germany and Canada.

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**: 
- New Row (https://api.seatable.io/reference/list-rows)
- New or Updated Row (https://api.seatable.io/reference/list-rows)
- Create row (https://api.seatable.io/reference/add-row)
- Update row (https://api.seatable.io/reference/update-row)

**Comment by LucBerge** [comment] 2024-02-20 09:47
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/3910

**Comment by sergio-eliot-rodriguez** [comment] 2024-03-28 20:41
Now integrated https://pipedream.com/apps/seatable

**Closed by sergio-eliot-rodriguez** 2024-03-28 20:41 UTC
Labels: enhancement, app, triaged, added to app backlog
