### ISSUE TITLE
[BUG] Require with a template string seems to not pull in the modules

### ISSUE THREAD

**Issue by togakangaroo** [PipedreamHQ/pipedream#714] opened 2020-12-21 04:30 UTC
**Describe the bug**
It seems like maybe the `require` statements are picked out with regex as opposed to an ast parser and the regex is not robust enough?

**To Reproduce**
I did 

```js
   Object.fromEntries = require(`fromentries`)
```

which gave me an error about `fromentries` not being installed.

Switching from backticks to quotes fixed it

**Expected behavior**

This should work. That is a perfectly acceptable way to require things. I do it regularly as I try to minimize the amount of different quoting options

**Additional context**

There are two ways I could recommend doing this better.

1. Use esprima to parse the script then just search for all invocations of the global `require`
2. When the script is saved, run it with a stubbed out `require` that simply records invocations. Stub out anything that might do an outgoing invocation and ignore all errors.

**Comment by tjk** [comment] 2020-12-22 07:45
Tracked this down -- a dependency just needs updating! Thank you very much for reporting! I'll follow up once the issue is fixed in production (hopefully tomorrow).

**Comment by tjk** [comment] 2020-12-23 04:12
This should be fixed now! Thanks again for reporting (and you can see the upstream bug here: https://github.com/replit/upm/pull/60)

<img width="847" alt="Screen Shot 2020-12-22 at 8 11 45 PM" src="https://user-images.githubusercontent.com/109224/102958532-f4075500-4491-11eb-80ca-a9f09947663b.png">

**Closed by tjk** 2020-12-23 04:12 UTC
Labels: bug
