### ISSUE TITLE
[Components] canva

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12997] opened 2024-07-24 22:34 UTC
# canva
## URLs
- https://www.canva.dev/docs/connect/quick-start/
#### Prompt
Creates a new design. The user should provide the props for design specifications such as document dimension, theme and template ID. The dimension and theme are mandatory while the template ID is optional.
#### URLs
- https://www.canva.dev/docs/connect/api-requests-responses/
- https://www.canva.dev/docs/connect/authentication/
- https://www.canva.dev/docs/connect/api-reference/authentication/
- https://www.canva.dev/docs/connect/api-reference/assets/
- https://www.canva.dev/docs/connect/api-reference/brand-templates/
- https://www.canva.dev/docs/connect/api-reference/designs/
- https://www.canva.dev/docs/connect/api-reference/design-imports/
- https://www.canva.dev/docs/connect/api-reference/exports/
#### Prompt
Exports an existing design from Canva. Requires a design ID to locate the specific design. Initiates an asynchronous job to handle the export function. An optional prop could be the requested file format for the export.
#### URLs
- https://www.canva.dev/docs/connect/api-requests-responses/
- https://www.canva.dev/docs/connect/authentication/
- https://www.canva.dev/docs/connect/api-reference/authentication/
- https://www.canva.dev/docs/connect/api-reference/exports/
#### Prompt
Initiates an asynchronous function to upload an asset to Canva. The user should provide a file path to point to the asset's location. Additional optional props may include a desired name for the asset in the Canva library.
#### URLs
- https://www.canva.dev/docs/connect/api-requests-responses/
- https://www.canva.dev/docs/connect/authentication/
- https://www.canva.dev/docs/connect/api-reference/authentication/
- https://www.canva.dev/docs/connect/api-reference/assets/
- https://www.canva.dev/docs/connect/appendix/scopes/

**Comment by michelle0927** [comment] 2024-07-25 19:15
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/12757

**Closed by michelle0927** 2024-07-25 19:15 UTC
Labels: triaged
