### ISSUE TITLE
[BUG] Pipedrive - New Deal - Max execution limit reached

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#4345] opened 2022-09-27 13:39 UTC
**Describe the bug**
When attempting to use the **Pipedrive - New Deal** source, I can develop with single events just fine.

But after deploying my workflow, the source fails with a maximum timeout error.

![image (23)](https://user-images.githubusercontent.com/2694734/192542092-f1d86964-4ddb-4a57-91db-220a77f902ed.png)

**Additional context**
Reported by user over email.

Might need to seed a Pipedrive account with many deals to reproduce the issue.

**Comment by Hassan-Abbas-SQA** [comment] 2022-09-27 20:50
@ctrlaltdylan i am unable to reproduce the bug
https://user-images.githubusercontent.com/104946677/192631581-90cbc1fe-1868-431f-a970-54b56ab09f0e.mov

that would be better if client shows us the version number of the source and proper steps to reproduce the issue with screencast

**Comment by dylburger** [comment] 2022-10-04 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2022-10-04 23:29 UTC
Labels: bug, question
