### ISSUE TITLE
[FEATURE] Loading page for HTTP response

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4280] opened 2022-09-19 11:37 UTC
**Is your feature request related to a problem? Please describe.**
When using a HTTP trigger with the `HTTP Response` set to `Return a custom response from your workflow`, the browser used to trigger the workflow loads with a white page while the Response is not sent. It could be a problem when the workflow takes 30 seconds to run. The user don't know if something when wrong and will probably refresh the page. He will trigger the workflow again and again without even knowing it.

**Describe the solution you'd like**
Display kind of a loading page with the steps being run (or not), so that the user knows that everything when rigth and he just have to wait to get the response.

**Do you have a workaround?**
No

**Comparable features in other tools?**
None from what I know

**Comment by Hassan-Abbas-SQA** [comment] 2022-09-19 18:50
@LucBerge are you referring to this issue ? #4279

**Comment by vunguyenhung** [comment] 2022-09-20 01:43
Hello @LucBerge, thank you for the suggestion. I'm able to reproduce this behavior that the browser is indicating loading for the request
![FireShot Capture 572 - Http_ Delay and return response - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191148136-9d3cfc6e-0f2f-47b6-8c3d-b68bf98c13f6.png)

![Screen Shot 2022-09-20 at 08 34 53](https://user-images.githubusercontent.com/18277920/191148025-b10f13a3-d662-4fe0-817e-bfcdaa8e9ffe.png)

I think the blank screen and loading indicator is a browser behavior, which Pipedream can not control. If Pipedream were to response a UI indicator in any form before sending a response back, it would conflict with the current request-response flow, which is not backward compatible. 

For this case, I think you can use a nicer HTTP client on the web such as: Postman for Web, RestMan browser extension. What do you think?

**Comment by LucBerge** [comment] 2022-09-20 07:52
> If Pipedream were to response a UI indicator in any form before sending a response back, it would conflict with the current request-response flow, which is not backward compatible.

Yes I know, but maybe you can make it backward compatible. I honestly don't know, it's up to the pipedream team.

> For this case, I think you can use a nicer HTTP client on the web such as: Postman for Web, RestMan browser extension. What do you think?

What is the difference if I use Postman web or RestMan browser ?

**A bit more of context:**

My flow is triggered from an airtable button. It takes 30 seconds to execute and I want the final result (computed in the last component) to be displayed as response to the HTTP trigger. I'm not the only one who clicks on the AirTable button as we are 4 collaborators to use AirTable and I cannot ask people to use an other browser.

**Alternative way to backward response:**

1. Trigger the workflow in a browser with immediate response. The response says that the workflow is in progress and you have to wait.
2. After an arbitrary delay, the page redirects to a second url.
   1. If the end of the workflow is not reached: The second url response is the same as the first one and you will be redirected again later on.
   2. If the end of the workflow is reached: The second url respond with my computed result.

**Comment by dylburger** [comment] 2022-09-25 01:33
Hi @LucBerge , unfortunately in HTTP, a client cannot receive two HTTP responses to a single request. This is the HTTP spec. [See details here](https://stackoverflow.com/a/46535111).

As that answer mentions, different protocols allow for this. If Airtable allowed you to listen to an SSE stream, for example, and update the value of a cell with some JavaScript that ran on new SSE events, you could update the value of the cell dynamically. [See the docs on `$.send.sse`](https://pipedream.com/docs/destinations/sse/#sending-data-to-an-sse-destination-in-workflows).

Another idea: the Pipedream workflow can respond with a static response immediately, allowing you to modify the value of the cell. Then you can use the Airtable API to write the final value you get. So instead of returning a second HTTP response, you'd push the data to Airtable to make the update via API.

Since the original request isn't possible, I'm closing this issue, but happy to discuss more ideas in Slack / Discourse.

**Closed by dylburger** 2022-09-25 01:33 UTC
Labels: enhancement, question
