### ISSUE TITLE
[Components] fireflies

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11363] opened 2024-04-09 08:54 UTC
# fireflies
## URLs
- https://docs.fireflies.ai/getting-started/introduction
#### Prompt
Emit new event when a meeting with transcripts is created. The applied props are the meeting ID, participant names, and start time. No additional props are required.
#### URLs
- https://docs.fireflies.ai/fundamentals/concepts
- https://docs.fireflies.ai/fundamentals/authorization
- https://docs.fireflies.ai/schema/meeting-attendee
- https://docs.fireflies.ai/schema/transcript
- https://docs.fireflies.ai/schema/user
#### Prompt
Retrieves the most recent meeting in Fireflies for a given user. No props required; directly pulls up the latest data.
#### URLs
- https://docs.fireflies.ai/fundamentals/authorization
- https://docs.fireflies.ai/schema/meeting-attendee
- https://docs.fireflies.ai/schema/user
#### Prompt
Searches for meetings in Fireflies using specific call details. These props can include time, place, participants, or any other relevant identifiers.
#### URLs
- https://docs.fireflies.ai/fundamentals/authorization
- https://docs.fireflies.ai/schema/aifilter
- https://docs.fireflies.ai/schema/audio-upload-status
- https://docs.fireflies.ai/schema/meeting-attendee
- https://docs.fireflies.ai/schema/sentence
- https://docs.fireflies.ai/schema/transcript
- https://docs.fireflies.ai/schema/summary
- https://docs.fireflies.ai/schema/user
#### Prompt
Creates, stores, transcribes and shares a new meeting in Fireflies from a given audio recording. This action requires an audio file prop in a supported format.
#### URLs
- https://docs.fireflies.ai/getting-started/quickstart
- https://docs.fireflies.ai/fundamentals/authorization
- https://docs.fireflies.ai/schema/audio-upload-status
- https://docs.fireflies.ai/schema/meeting-attendee
- https://docs.fireflies.ai/schema/transcript

**Comment by michelle0927** [comment] 2024-04-09 16:13
Closing issue as this appears to be a duplicate of https://github.com/PipedreamHQ/pipedream/issues/11313

**Closed by michelle0927** 2024-04-09 16:13 UTC
Labels: triaged
