### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by getthenightstarted** [PipedreamHQ/pipedream#5627] opened 2023-03-06 18:47 UTC
**Describe the bug**
When using the MongoDB integration, any attempt to search_documents returns an error message stating "The requested module 'mongodb' does not provide an export named 'ObjectID'"

**To Reproduce**
1. Go to Pipedream, create a new workflow.
2. Add a step, choosing 'MongoDB'
3. Select 'search_documents'
4. Even without any filters, the bug is triggered and the error message is shown.

**Expected behavior**
MongoDB documents are returned from the connection.

**Screenshots**
<img width="905" alt="image001" src="https://user-images.githubusercontent.com/112399182/223202556-969955f9-8a33-4a59-be9d-e5eb9ee9e687.png">

**Comment by vunguyenhung** [comment] 2023-03-07 17:02
Hello @getthenightstarted, I believe Pipedream has recently shipped a fix for this issue. Would you mind [updating version of your action](https://pipedream.com/docs/workflows/steps/actions/#updating-actions-to-the-latest-version)?

I couldn't reproduce this for the newest version.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/18277920/223494570-96d26240-c3a0-4a4c-a570-c4f6e093ffa4.png">

**Comment by dylburger** [comment] 2023-03-14 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2023-03-14 23:29 UTC
Labels: bug, question
