### ISSUE TITLE
[Components] chatbotic

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#8850] opened 2023-11-07 00:55 UTC
# chatbotic
#### Prompt
Emit new event when a new lead's email or mobile number is captured in Chatbotic AI chatbot widget. Props required: Access to the chatbot widget to track and capture the details of new leads.

**Comment by michelle0927** [comment] 2024-12-14 21:45
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/13371

**Closed by michelle0927** 2024-12-14 21:45 UTC
Labels: triaged
