### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#9080] opened 2023-11-23 06:32 UTC
### App
Notion
https://developers.notion.com/reference/property-object#date-configuration

### Sources
N/A

### Actions
When setting the date property during a "create page from database call" you only get the option to set an arbitrary date. Zapier gives you the option to set the start date, end date, and include the time.

Would be good if pipedream also did that.

**Comment by michelle0927** [comment] 2024-12-14 21:44
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/14451

**Closed by michelle0927** 2024-12-14 21:44 UTC
Labels: trigger / source, triaged, user request, actions
