### ISSUE TITLE
[BUG] Not able to create Telegram Bot: New Channel Updates trigger

### ISSUE THREAD

**Issue by dannyroosevelt** [PipedreamHQ/pipedream#4266] opened 2022-09-16 19:27 UTC
Based on the error message it seems related to my same bot token being used in a different Telegram trigger?

![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/190715764-77443cbd-a4ab-4ca0-9e4b-5e2e4b1288e0.png)

**Comment by vunguyenhung** [comment] 2022-09-20 00:59
I confirm that I can reproduce the issue when creating 2 Telegram sources.
The first source: New Channel Update is created successfully
![FireShot Capture 565 - Source_ New Channel Updates (Instant) - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191143686-b92f8d96-65f8-4b81-a25b-1ba77605aefa.png)

Then while the first source: New Channel Update is active, create the second source: New Channel Update. Observe the error
![FireShot Capture 564 - New Source - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191143652-28a47109-e4bd-42cf-87ee-f4584ba9ed39.png)

When I inactivate the first source: New Channel Update, the second source: New Channel Update is created successfully
![FireShot Capture 566 - Source_ ChannelUpdates#2 - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191143863-9d042d3b-0efe-4c6a-b2bd-78b4672c31d5.png)

When the second source: New Channel Update is active, I created the third source: New Message Update and observed the same error
![FireShot Capture 568 - New Source - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/191144112-31a9e8f0-cd81-44c3-9542-7753693fd1da.png)

It seems like that only one Telegram source is eligible at a moment, this is due to Telegram limitation on their webhook usage that we couldn't change for now. Hence, I would suggest we catch this error and provide a clearer message for the user indicate the next action, for example:
```
Failed to create the source since there's another Telegram Bot source is in active. Considering reusing the existing source, or inactive the first source and try again
```

@dannyroosevelt what do you think?

**Comment by dannyroosevelt** [comment] 2022-09-21 02:32
Ah good catch, darn. Can you add a ticket to the board to make that update? We should Throw a Configuration error for this ideally: https://pipedream.com/docs/code/nodejs/#configuration-error

Text: 
```
[Telegram only supports](https://core.telegram.org/bots/api#setwebhook) a single webhook at a time, for a given Bot. To get around this, you can reuse an existing Telegram Bot source or disable the active source and try again. [View all your sources here](https://pipedream.com/sources).
```

**Comment by vunguyenhung** [comment] 2022-09-21 04:56
Thank you for confirming @dannyroosevelt. I have created the issue here: https://github.com/PipedreamHQ/pipedream/issues/4300. 

Hence I will close this Github issue 🙏

**Closed by vunguyenhung** 2022-09-21 04:56 UTC
Labels: bug, triaged
