### ISSUE TITLE
[BUG] Cannot select long console  logs to copy

### ISSUE THREAD

**Issue by rcmontrose** [PipedreamHQ/pipedream#1104] opened 2021-03-19 00:03 UTC
**Describe the bug**
If you have a long console log (e.g. 77 lines), when you attempt to select the log text to copy it, it copies intermittent blocks of text and you cannot select the entire log.

**To Reproduce**
1. Create an action with over 50 lines to the console log.
2. Attempt to select all 50 lines of output.
3. If you copy the selected text, you only get fragments of the console log.

**Expected behavior**
1. I could start selecting the text, and it would scroll down and allow the text selection to continue to the end, and then I could Cntrl-C to copy the text, and then paste it into a notepad.
2. Better yet, allow the user to enter Control-A to select all the text in the log, and then Control-C to copy it to the clipboard.
3. Best implementation would be to have a button to "Copy value", like on the Events, that copies the entire Console.log to the  clipboard.

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/59274633/111712692-25d35200-881c-11eb-97cc-04c56a339b53.png)
[copied text.txt](https://github.com/PipedreamHQ/pipedream/files/6167799/copied.text.txt)

See the attached file for what is actually selected (just the shaded text)

**Desktop (please complete the following information):**
 - OS: Windows 10 19H2
 - Browser Chrome
 - Version 89.0.4389.82

**Additional context**

**Comment by dylburger** [comment] 2021-03-19 00:21
Thanks @rcmontrose, I can reproduce. I shared with the team and we'll discuss potential solutions.

**Comment by dylburger** [comment] 2021-04-22 22:41
@rcmontrose I just wanted to let you know that we've added this to our internal backlog. Ideally, we'd have a **Copy Logs** button or a way to get access to the entire set of logs. No ETA at the moment, but I'll update you when we have something.

**Comment by dylburger** [comment] 2022-04-23 23:48
Closing since we've changes the Logs UI in v2. If this is still an issue in v2, we can address in another ticket

**Closed by dylburger** 2022-04-23 23:48 UTC
Labels: bug, new builder
