### ISSUE TITLE
[BUG] Dropbox - New File source did not emit new event when the user uses Dropbox PC File sync

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10247] opened 2024-02-06 08:27 UTC
**Describe the bug**
When the user upload files using Dropbox app: https://www.dropbox.com/install. Our trigger did not emit new event. (The Dropbox web works just fine)

Please see this loop video: https://www.loom.com/share/10155c9fa967408d938116f4f2337544?sid=e89ef6cc-56f5-4ca1-a457-d25f8734bf87

**Additional context**
Raised by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1707203686145179

**Comment by malexanderlim** [comment] 2024-02-07 01:07
Unable to reproduce the issue using a new workflow, with New File source. Closing this issue for now as the user has reported using a workaround for now.

**Closed by malexanderlim** 2024-02-07 01:07 UTC
Labels: bug, triaged
