### ISSUE TITLE
[Components] flash-by-veloraai

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14439] opened 2024-10-25 23:59 UTC
# flash-by-veloraai
#### Prompt
Send customer-related feedback to the Flash system for comprehensive analysis. The props required would be 'feedback-content' describing the feedback and 'customer-id' for associating the feedback with the right individual. An optional prop could be 'customer-email'.
#### Prompt
Transfer a contact call transcript to the Flash system for thorough analysis. Essential props to configure would be 'transcript-content' that contains the actual transcript and 'call-id' to link the transcript to the specific call. 'Caller-id' could be an optional prop for detailed profiling.

**Comment by michelle0927** [comment] 2024-10-28 18:31
> Hi @michelle0927 I think I forgot to moved #14425 to ready for PR review, can we take mine instead Michelle since I have more props in the **Add Feedback** action?

Yes, sorry, I didn't notice this was a duplicate. I left out some props because they were giving me internal server errors. I'm glad you got them working!

**Comment by michelle0927** [comment] 2024-10-28 18:31
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/14425

**Closed by michelle0927** 2024-10-28 18:31 UTC
