### ISSUE TITLE
[Components] liveswitch

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14355] opened 2024-10-18 17:16 UTC
# liveswitch
#### Prompt
Emit new event when a new contact is added. Required props: contact data. Optional props: custom fields, notes.
#### Prompt
Emit new event when an existing contact is updated. Required props: contact id, updated fields. Optional props: comments, previous contact data.
#### Prompt
Emit new event when a new conversation is started. Required props: conversation data. Optional props: participant data, message content.
#### Prompt
Creates a new contact within the Liveswitch Contact and Concierge system. The required props are name, email, and the optional prop is phone.
#### Prompt
Finds an existing contact in the Liveswitch Contact and Concierge system by their phone number. The required prop is phone number.
#### Prompt
Creates a new conversation within the Liveswitch Contact and Concierge system. The required props are either phone or contact id, but not both.

**Comment by michelle0927** [comment] 2024-10-21 20:58
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/13859?

**Closed** 2024-11-19 01:57 UTC
Labels: triaged
