### ISSUE TITLE
[BUG] Failed to create source Github: New Card in Column for a specific Github Project

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#3494] opened 2022-07-21 06:35 UTC
**Describe the bug**
On Pipedream `@pd-component-dev` org, I have created a new workflow and attempted to create a source **Github: New Card in Column** for Pipedream Github Project: **Component (Source and Action) Backlog**, but there's an error when I tried to save the Source

**To Reproduce**
1. Login into Pipedream's `@pd-component-dev` org
2. Create a new Workflow
3. Add the trigger Github: New Card in Column with the information in the image below
5. Observe the error: `HttpError: Not Found`
<img width="608" alt="Screen Shot 2022-07-21 at 13 23 28" src="https://user-images.githubusercontent.com/18277920/180144980-ba717ffd-5997-4491-8fa6-b7793d793e42.png">

**Expected behavior**
The source Github: New Card in Column should be created successfully, and is triggered when a card created or moved into the column

**Additional context**
I successfully created the source Github: New Card in Column on my personal account, with personal Github Project. So I suspect this issue occurred specifically for Pipedream Github Project
<img width="725" alt="image" src="https://user-images.githubusercontent.com/18277920/180145460-1f02afbc-cd30-48fa-84d8-dfe83288aaf6.png">

**Comment by andrewjschuang** [comment] 2022-07-26 12:34
Can confirm I had the same issue

**Comment by alysonturing** [comment] 2022-08-03 13:08
I'll try to fix this bug

**Comment by alysonturing** [comment] 2022-08-08 15:39
I also successfully created the source `Github: New Card in Column` on my personal account, with personal Github Project. **But with further investigation, I became aware that the webhook endpoint answers: `404 Resource not found` when you don't have enough administrative permissions.**

- So I'd say it's not a bug, we simply doesn't have permissions to create webhooks into pipedream's organization 
https://docs.github.com/en/rest/webhooks/repos#create-a-repository-webhook
https://github.com/orgs/community/discussions/26368

**Comment by alysonturing** [comment] 2022-08-08 15:42
@andrewjschuang @vunguyenhung 
with the previous informations, how we can proceed with this task, should I close it?

**Comment by vunguyenhung** [comment] 2022-08-08 15:51
Hello @alysonturing, thank you for checking! I think we can improve our error message to inform the user that their connected Github account might not have enough permissions. For example, the error message can be:
```
Error occurred: HttpError: Not found. This might due to your connected Github account does not have enough permission to perform this action.
```

**Comment by alysonturing** [comment] 2022-08-08 15:52
> Hello @alysonturing, thank you for checking! I think we can improve our error message to inform the user that their connected Github account might not have enough permissions. For example, the error message can be:
> 
> ```
> HttpError: Not found. 
> This might due to your connected Github account does not have enough permission to perform this action.
> ```
> 
> @alysonturing @andrewjschuang what do you think?

I agree with that

**Comment by andrewjschuang** [comment] 2022-08-08 16:00
It's strange because Danny gave the `pd-component-dev` org account the required permissions, but it still can't create the webhook for the project. I've added you to the org, can you please check on that?

**Comment by alysonturing** [comment] 2022-08-08 16:27
> It's strange because Danny gave the `pd-component-dev` org account the required permissions, but it still can't create the webhook for the project. I've added you to the org, can you please check on that?

I tried again with my account, I'm part of the pipedream's organisation, still doesn't work... Can you check my permissions to create webhooks?

**Comment by andrewjschuang** [comment] 2022-08-19 14:57
From this [link](https://docs.github.com/en/get-started/customizing-your-github-workflow/exploring-integrations/about-webhooks):

> Tip: Only members with owner privileges for an organization or admin privileges for a repository can manage webhooks for an organization. For more information, see "[Roles in an organization](https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/roles-in-an-organization)."

I have tested this, and for organization repositories, the token must have **admin privileges** (maintainer is not enough) and at least `public_repo` and `read:org` scopes to create webhooks, along with others required by the trigger.

Closing this since the underlying issue and fix is described above.

**Closed by andrewjschuang** 2022-08-19 14:57 UTC
Labels: bug, blocked, triaged
