### ISSUE TITLE
[Components] docnify

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14205] opened 2024-10-03 20:33 UTC
# docnify
## URLs
- https://docs.documenso.com/developers/public-api https://app.documenso.com/api/v1/openapi

**Comment by michelle0927** [comment] 2024-10-23 18:01
Duplicate of https://github.com/PipedreamHQ/pipedream/pull/14203

**Closed by michelle0927** 2024-10-23 18:01 UTC
Labels: triaged
