### ISSUE TITLE
[BUG] IMAP connection is healthy, but no Mailboxes are found

### ISSUE THREAD

**Issue by krisee99** [PipedreamHQ/pipedream#2221] opened 2022-02-10 10:25 UTC
**Describe the bug**
Hy! I created a fresh account for an IMAP connection, then I tried to make a source of it, and after clicking on the Mailboxes dropdown an error was shown by the app.

**To Reproduce**
1. Create an IMAP account
2. Try to create a source of the created "account"
3. Select Mailbox

**Expected behavior**
A list of the available mailboxes

**Screenshots**
![image](https://user-images.githubusercontent.com/20201094/153384923-2d22b895-366f-4cac-91e1-40e0a24876c2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: latest

**Additional context**
Under the "accounts" page the connection is marked as Healthy and I've connected multiple mail clients using the same credentials.

**Comment by js07** [comment] 2022-02-11 17:37
For your IMAP account in Pipedream, which port are you using? 143? I'm wondering if the issue is related to the connection protocol being used for the IMAP connection.

I created a workflow that uses different configuration options for the IMAP connection. Would you mind running it to see if that configuration works?
https://pipedream.com/@js071/imap-get-mailboxes-test-p_ezCJLAR

**Comment by krisee99** [comment] 2022-02-15 11:30
@js07, I'm currently using port 993 and it's for TLS, however, the mailing server provides a non TLS connection under port 143 but it's not working either. Copied the workflow that you've linked but it throws the same error if I try to add it as a source.

**Comment by krisee99** [comment] 2022-02-15 11:32
sorry, I forgot: If I try it out under port 143 it throws the following error:

139860292999040:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

**Comment by js07** [comment] 2022-02-17 03:06
@krisee99 I updated the code step in the [workflow](https://pipedream.com/@js071/imap-get-mailboxes-test-p_ezCJLAR) to create an IMAP connection with the implicit `tls` option set to `false` when the `port` isn't 993.
If you get a chance, let me know if that fixes the error for you.

**Comment by dylburger** [comment] 2022-02-24 23:23
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2022-02-24 23:23 UTC
Labels: bug, question
