### ISSUE TITLE
[Components] sendblue

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13285] opened 2024-08-08 18:55 UTC
# sendblue
#### Prompt
Emit new event when an inbound message is received. No props are needed to configure this trigger as it directly responds to incoming messages.
#### Prompt
Sends an iMessage or SMS to a specified phone number. Required prop: 'phone number'. Optional props: 'message content', 'message type' (i.e., SMS or iMessage).
#### Prompt
Retrieves the list of existing contacts from Sendblue. No required props. This action helps in maintaining and managing your contact list effectively.
#### Prompt
Sends a message to an iMessage group. Required props: 'group identifier', 'message content'. This action lets you communicate with multiple contacts simultaneously.

**Comment by michelle0927** [comment] 2024-12-14 21:48
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/14949

**Closed by michelle0927** 2024-12-14 21:48 UTC
Labels: triaged
