### ISSUE TITLE
[ACTION] insert many rows in Supabase tabel

### ISSUE THREAD

**Issue by jamesjokr** [PipedreamHQ/pipedream#7750] opened 2023-08-25 08:37 UTC
**Is there a specific app this action is for?**
how to insert many rows in Supabase tabel

**Please provide a link to the relevant API docs for the specific service / operation.**

**Comment by michelle0927** [comment] 2024-11-14 19:16
Duplicate of #14646

**Closed by michelle0927** 2024-11-14 19:16 UTC
Labels: enhancement, help wanted, good first issue, action, triaged
