### ISSUE TITLE
Obsidian

### ISSUE THREAD

**Issue by shawnpjennings** [PipedreamHQ/pipedream#12530] opened 2024-06-22 17:16 UTC
**Obsidian**

**https://docs.obsidian.md/Home**

**Just getting started with your platform but surprised this service isn't offered**

**Are there specific actions, or triggers, you'd like to see for this app? Please let us know here or use the Action and Trigger issue templates to open requests for each!**

**Comment by sergio-eliot-rodriguez** [comment] 2024-06-22 18:47
Duplicate of #6144

**Closed by sergio-eliot-rodriguez** 2024-06-22 18:47 UTC
Labels: enhancement, app
