### ISSUE TITLE
[BUG] Discord - New Message does not emit new event for new message

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5906] opened 2023-04-01 18:11 UTC
**Describe the bug**
Discord - New Message does not emit new event for new message

**To Reproduce**
1. On Pipedream [source page](https://pipedream.com/sources), create a new Discord - New Message source. Select a connected Discord account and channel
![image](https://user-images.githubusercontent.com/18277920/229304461-2a412374-54a1-499a-928e-cf0392bf1e6e.jpeg)
2. On discord, send some message to the channel
![image](https://user-images.githubusercontent.com/18277920/229304533-58372a8d-167b-4e3d-903f-208cbb49ee92.jpeg)
3. Observe that there's no event emitted
4. The source log is blank
![image](https://user-images.githubusercontent.com/18277920/229307370-aeb8c6fc-b9a3-4824-8662-7c8833233788.jpeg)

**Expected behavior**
New event should be emitted when new message is sent

**Additional context**
Reported by a user here https://pipedream.com/community/t/discord-test-event-new-message/5376

**Comment by lcaresia** [comment] 2023-04-03 13:35
I can't reproduce the bug

![image](https://user-images.githubusercontent.com/12402324/229525744-158cda50-8e5e-493c-bedd-d9a4baff2475.png)


Cc: @vunguyenhung @dannyroosevelt

**Comment by dannyroosevelt** [comment] 2023-04-03 19:33
FYI we deployed a fix for this last night

**Closed by dannyroosevelt** 2023-04-03 19:33 UTC
Labels: bug, triaged, prioritized
