### ISSUE TITLE
[Components] thinkific

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10990] opened 2024-03-14 21:43 UTC
# thinkific
## URLs
- https://developers.thinkific.com/api/api-documentation/
#### Prompt
Emit new event when a new purchase has been made. Props include the order details such as product name, total amount, etc.
#### Prompt
Emit new event when a user enrolls in your course. Props include the course id and user details, which can further be utilized.
#### Prompt
Emit new event when a user completes a course. Required props would be the course id to identify the course and the user id to track the user who has completed the course.
#### Prompt
Enroll a student in a course or bundle. Props required: user ID or email, course or bundle ID.
#### Prompt
Create a new user object. Props required: user data fields (such as name, email).
#### Prompt
Update existing user details. Props required: user ID, updated user data fields.

**Comment by michelle0927** [comment] 2024-03-19 20:28
API access requires a paid account - https://www.thinkific.com/pricing/

**Comment by michelle0927** [comment] 2024-04-12 20:12
Closing as this is a duplicate of https://github.com/PipedreamHQ/pipedream/issues/11212

**Closed by michelle0927** 2024-04-12 20:12 UTC
Labels: blocked, triaged, paid-account-needed
