### ISSUE TITLE
[Components] supabase_management_api

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13639] opened 2024-08-21 19:34 UTC
# supabase_management_api
## URLs
- https://supabase.com/docs/reference/api/introduction

**Comment by michelle0927** [comment] 2024-08-26 20:04
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/13637

**Closed by michelle0927** 2024-08-26 20:04 UTC
