### ISSUE TITLE
[BUG] Postgres connection failure on Heroku Postgres instance

### ISSUE THREAD

**Issue by huevoncito** [PipedreamHQ/pipedream#3269] opened 2022-06-29 13:31 UTC
**Describe the bug**
When connecting to a postgres database, receiving error "Connection terminated unexpectedly". The connection strings work in the command line and through Datagrip. There are no IP restrictions on the db. I have tried deleting and reconnecting sources to no avail. It connected successfully once and retrieved past events, but subsequent events I added to the db were not picked up by the trigger and the error subsequently returned.

**To Reproduce**
1. Setup a new workflow and connect a postgres DB
2. Try to select a table. The app fails to load the table but does not say why.
3. Navigate to the source page and you can see the error in the config section.

**Expected behavior**
Connection should succeed.

**Screenshots**
Screenshot from the sources view.
![Screen Shot 2022-06-29 at 09 27 18](https://user-images.githubusercontent.com/4283521/176447988-9d2caa8a-2505-4fd2-af33-f41e90c4fd1c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Brave
 - Version 1.39.122

**Additional context**

**Comment by vunguyenhung** [comment] 2022-06-29 15:18
Hello @huevoncito, thanks for raising this issue. I'm trying to reproduce your issue but couldn't. May I ask for the following information on your side:
- Number of connections on your database when the source is executed or when you fetching the table, you can query using the following SQL statement:
```
SELECT sum(numbackends) FROM pg_stat_database;
```
- The connection limit of your database. You can query this value using the following SQL statement:
```
SHOW max_connections
```

**Reproduction Steps:**
- I created a New or Updated Row source, and tried to create/update many rows for new events to be emitted. I have waited 10 mins and tried again to see if the connection terminated because of idle time exceeded, though new events were still emitted
![FireShot Capture 063 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/176471543-13b2d26e-e71d-4c47-b100-0b85cbd35a79.png)

- I created a New Row action, and tried to fetch the table and execute action many times. I have waited 10 mins to see if the connection terminated because of idle time exceeded, though the action is still executed successfully
![FireShot Capture 062 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/176471396-9471d195-c801-483a-b23d-a025a7f71a6a.png)

**Comment by huevoncito** [comment] 2022-06-29 16:14
Thanks for your very quick reply, @vunguyenhung. It's showing 500 max connections with 142 activated.

I just removed all sources and tried to build a new workflow. Within that workflow, I added a new source. This is what it shows. I will investigate further to see if the problem may be originating on our side.

![Screen Shot 2022-06-29 at 12 11 16](https://user-images.githubusercontent.com/4283521/176484636-68b12b66-a134-4417-ad31-567d04734510.png)

**Comment by vunguyenhung** [comment] 2022-06-29 16:16
Hello @huevoncito, I'm able to reproduce this issue using Heroku Postgres instance
![image (4)](https://user-images.githubusercontent.com/18277920/176485299-bcdcc7ea-97b9-4893-a42e-c2eb07925edb.png)

I will escalate this issue to our component dev! We will make any update into this Github issue 🙏

**Comment by vunguyenhung** [comment] 2022-06-29 16:46
Hello again @huevoncito, as a workaround for now when the issue is not fixed on our side, I suggest to use [ElephantSQL](https://www.elephantsql.com/), I have tested and it works fine :pray:

**Comment by huevoncito** [comment] 2022-06-29 17:35
Got it @vunguyenhung. Thank you for the very quick support. Really appreciate it.

**Closed as completed** 2022-07-12 15:22 UTC
Labels: bug, triaged
