### ISSUE TITLE
[Components] affinity

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11402] opened 2024-04-11 00:10 UTC
# affinity
## URLs
- https://api-docs.affinity.co/#introduction
#### Prompt
Emit new event when a new organization is added. No props required.
#### Prompt
Emit new event when a new opportunity is created. Props required are title and description of opportunity.
#### Prompt
Emit new event when a field value changes. Required props are field name and new value. Optional prop could be previous value.
#### Prompt
Creates a new person entry. Requires an input prop for person details. Use the 'search' function to avoid duplicate entries.
#### Prompt
Updates the fields of a person, organization, or opportunity. Requires entity identification information and the updated fields as input props.
#### Prompt
Creates a new opportunity entry. Requires an input prop for opportunity details. Use the 'search' function to avoid duplicate entries.

**Comment by michelle0927** [comment] 2024-12-14 22:08
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/3542

**Closed by michelle0927** 2024-12-14 22:08 UTC
Labels: blocked, triaged, paid-account-needed
