### ISSUE TITLE
[FEATURE] Improve the performance of the workflow log

### ISSUE THREAD

**Issue by nachocab** [PipedreamHQ/pipedream#562] opened 2020-10-19 07:55 UTC
When loading a workflow that has multiple runs, it can take up to 30 seconds to load all those instances.

For example, this is real time (~15 seconds): 
![Oct-19-2020 09-53-43](https://user-images.githubusercontent.com/27538/96416984-07c3e000-11f1-11eb-982e-d85127dabb38.gif)

I don't know how feasible it is technically, but an easy fix would be showing the results from most to least recent. A different/complementary alternative would be caching.

**Comment by dylburger** [comment] 2021-01-28 05:55
Duplicate of #92 . If you don't mind, please follow that issue for updates.

**Closed by dylburger** 2021-01-28 05:55 UTC
Labels: enhancement
