### ISSUE TITLE
[Components] clicksend

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11046] opened 2024-03-19 17:22 UTC
# clicksend
#### Prompt
Emit new event when a new incoming SMS is received. No required props.
#### Prompt
Emit new event when a new incoming SMS is received. No required props.
#### Prompt
Emit new event when a new voice message is either received or sent. No required props.
#### Prompt
Creates a new contact on your clicksend account. Required props: contact, primarily composed of name, phone, and email. Optional props: custom fields for more detailed contact information.
#### Prompt
Sends a new SMS to a specified recipient using clicksend. Required props: destination number, message content. Optional props: sender id, sending speed.
#### Prompt
Sends a physical postcard globally. PDF document printed and delivered via post. Required props: PDF document, recipient address. Optional props: personalised message content.

**Comment by michelle0927** [comment] 2024-03-20 21:29
This is a duplicate of https://github.com/PipedreamHQ/pipedream/issues/10991

**Closed by michelle0927** 2024-03-20 21:29 UTC
Labels: triaged
