### ISSUE TITLE
[FEATURE] Filter HTTP requests

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#9233] opened 2023-12-08 20:16 UTC
**Is your feature request related to a problem? Please describe.**
I would like to be able to filter HTTP requests within my Webhook triggers in Pipedream.

For example, I want to be able to ignore HTTP requests if the method is not a `POST`, or perhaps skip the request if there is a specific value in the payload of the body.

**Describe the solution you'd like**
I would like additional controls within the native Pipedream HTTP Webhook trigger to ignore (aka filter) certain HTTP requests based on criteria I outline.

**Do you have a workaround?**
No, because even if I create a custom source to ignore requests, then I'm charged for the usage of the trigger because it's not a publicly available source.

**Comparable features in other tools?**
HookDeck has a filter feature on their sources to ignore incoming webhooks.

**Comment by dylburger** [comment] 2023-12-08 20:32
Duplicate of #556

**Closed by dylburger** 2023-12-08 20:32 UTC
Labels: enhancement, triaged, tracked internally
