### ISSUE TITLE
[BUG] Can not execute `pd dev` on You need a budget source

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#4089] opened 2022-08-25 16:30 UTC
**Describe the bug**
Can not execute `pd dev` on You need a budget source. Error shown `panic: graphql: Cannot return null for non-nullable field Selectable.label`

**To Reproduce**
1. Please **delete** any existing Pipedream accounts for You need a budget
2. Clone `pipedream` Github repo, then `cd components/you_need_a_budget`
3. Execute `pd dev <path-to-source>` to deploy as dev a source. .i.e `low-account-balance`
4. On the command line prompt, connect to the **new** You need a budget account, then the source should be deployed successfully <img width="1728" alt="image" src="https://user-images.githubusercontent.com/18277920/186718926-66570587-78b3-40a0-a8cd-c5261ee37a95.png">
5. Press `Ctrl + D` to return to the command input, execute `pd dev <path-to-source>` to deploy the source as dev again
6. Observe the error <img width="1728" alt="image" src="https://user-images.githubusercontent.com/18277920/186719243-e6dadfad-6b2c-47d0-9763-9786f97edf00.png">

**Expected behavior**
The source should be deployed successfully every time

**Additional context**
Upon further investigation, @andrewjschuang figured out that the reason is the default nickname of You Need a Budget Account on Pipedream 
![FireShot Capture 157 - Connected Accounts - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/186719604-951dad9c-cdfe-4bd1-8153-7d55d9ed227b.png)

After changing the nickname, I can deploy the source again
![FireShot Capture 158 - Connected Accounts - Pipedream - pipedream com](https://user-images.githubusercontent.com/18277920/186719920-7d0ea947-02d6-4c31-bcc4-76d6a54feccf.png)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/18277920/186720015-b216c06b-8d1f-4aa5-bf96-17fbf9f02e72.png">

**Comment by dannyroosevelt** [comment] 2022-08-30 19:06
And Hubspot it sounds like

**Comment by dannyroosevelt** [comment] 2022-08-30 19:07
I don't understand -- is there any reason this would be app-specific?

**Comment by andrewjschuang** [comment] 2022-08-30 19:15
> I don't understand -- is there any reason this would be app-specific?

Not sure, looks like some apps, when you create a new account, they don't automatically create a nickname for that account. For example, this one was auto-generated:

![Screen Shot 2022-08-30 at 4 14 33 PM](https://user-images.githubusercontent.com/15385076/187523911-d1a4255a-adc0-4c3e-a332-314017e25f66.png)

**Comment by dylburger** [comment] 2022-09-30 00:31
Duplicate of #2565

**Closed by dylburger** 2022-09-30 00:31 UTC
Labels: bug, triaged, tracked internally
