### ISSUE TITLE
[Components] timing

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11366] opened 2024-04-09 08:56 UTC
# timing
## URLs
- https://web.timingapp.com/docs/#introduction
#### Prompt
Emit new event when a new project is created. No props are required.
#### URLs
- https://web.timingapp.com/docs/collection.json
- https://web.timingapp.com/docs/openapi.yaml
#### Prompt
Emit new event when a new timer is started. No props are required.
#### URLs
- https://web.timingapp.com/docs/collection.json
- https://web.timingapp.com/docs/openapi.yaml
#### Prompt
Emit new event when a new time entry is made. No props are required.
#### URLs
- https://web.timingapp.com/docs/collection.json
- https://web.timingapp.com/docs/openapi.yaml
#### Prompt
Creates a new project. Requires 'project name' prop.
#### URLs
- https://web.timingapp.com/docs/collection.json
- https://web.timingapp.com/docs/openapi.yaml
#### Prompt
Starts a new running timer. Requires 'project name' prop. Optional 'description' prop can be added.
#### URLs
- https://web.timingapp.com/docs/collection.json
- https://web.timingapp.com/docs/openapi.yaml
#### Prompt
Stops the running timer. No additional props needed.
#### URLs
- https://web.timingapp.com/docs/collection.json
- https://web.timingapp.com/docs/openapi.yaml

**Comment by michelle0927** [comment] 2024-04-09 16:11
Closing issue as this appears to be a duplicate of https://github.com/PipedreamHQ/pipedream/issues/11316

**Closed by michelle0927** 2024-04-09 16:11 UTC
Labels: triaged
