### ISSUE TITLE
[BUG] Source: IMAP - Can't select Mailbox

### ISSUE THREAD

**Issue by david-novafacile** [PipedreamHQ/pipedream#4382] opened 2022-09-30 11:34 UTC
**Describe the bug**
It's not possible to get Mailboxes  from IMAP email account. 

* With Port 143 the following error appear: 
 `139819960051584:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: `
* With Port 993: 
 `Error, please try again`

Feedback from email provider:
 > You can use TLS 1.2 and TLS 1.3 on the server. The error message indicates an outdated SSL version.

**To Reproduce**
1. Got to Accounts
2. Add a imap account with port 993 or 143
3. Got Source
4. Add a new IMAP Source (choose "*New Email*")
5. Select IMAP Account
6. Try to select mailbox --> see error

**Expected behavior**
Possibility to choose a mailbox

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 105.0.1, Chrome 106.0.5249.62

**Additional context**
email provider support has been requested
Feedback from email provider:
 > You can use TLS 1.2 and TLS 1.3 on the server. The error message indicates an outdated SSL version.

Feeback from Piere in Pipedream support forum with an assumption (https://pipedream.com/community/t/imap-connection-error-ssl3-get-record-wrong-version-number/3374/4)
> It may be that the underlying NPM package for connecting to mailboxes has an issue: 
[PipedreamHQ/pipedream/blob/master/components/imap/imap.app.mjs#L1](https://github.com/PipedreamHQ/pipedream/blob/master/components/imap/imap.app.mjs#L1)

**Comment by Hassan-Abbas-SQA** [comment] 2022-09-30 21:03
iam unable to reproduce the bug 
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/104946677/193355801-d2ea1600-9b97-4720-9ee4-d5227b80b557.png">

**Comment by david-novafacile** [comment] 2022-09-30 21:32
It's still there. It's not Gmail or similar. It's an email account at a big german web hosting provider (all-inkl.com).

![grafik](https://user-images.githubusercontent.com/43939617/193359043-985aede6-e3f1-4f70-a3d1-02ada66c34fb.png)

**Comment by Hassan-Abbas-SQA** [comment] 2022-09-30 21:53
@david-novafacile can you please try the solution given here https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number

**Comment by david-novafacile** [comment] 2022-09-30 22:30
Sorry, I don't know, how I can test this. I only add a new source in pipedream (and choose imap -> new email) and at the email hosting provider I only can add/delete an email account or change email credentials. 

Is there a special need for the imap server url? I set it up with something like `xyz.serverdomain.tld` (no protocol) like it works in every other tool or service.

**Comment by Hassan-Abbas-SQA** [comment] 2022-09-30 22:40
i want you to try out gmail IMAP as it works for me Can you please follow these steps?
1: <img width="743" alt="image" src="https://user-images.githubusercontent.com/104946677/193365419-5c009831-e7d9-4a37-a151-2a7e404807ab.png">
2: Host : imap.gmail.com
3: Port: 993
4: email should be your gmail 
5: password should be generated as app password from your gmail account 
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/104946677/193365621-17155926-cdd7-4cb2-b504-ddb8c29361b4.png">
and test this just to know that issue is from pipedream action or your connection account as this method worked for me

**Comment by david-novafacile** [comment] 2022-10-01 06:17
Ah okay. IMAP with Gmail works:

![grafik](https://user-images.githubusercontent.com/43939617/193395638-e4b2c2ad-b362-44bc-97fe-ff90eb0c46af.png)

**Comment by DilanAthukorala** [comment] 2022-10-03 16:31
@david-novafacile Did you able to resolve the issue? If so we can close this ticket.

**Comment by david-novafacile** [comment] 2022-10-03 16:41
Hi, no the error is still there. 

I just tested as wished with gmail but with the other hosting provider (as described) it doesn't work.

**Comment by DilanAthukorala** [comment] 2022-10-04 18:33
@Hi @david-novafacile I am not able to reproduce the error, the source is working with other email providers (gmail, outlook). It could be a mismatch with the underlying server's TLS version. I will add this to our backlog and prioritize it so our dev team can further investigate this and confirm the root cause. Please follow this ticket for updates.

**Closed** 2022-10-10 16:21 UTC
Labels: bug, triaged
