### ISSUE TITLE
[BUG] Python | Error: read ECONNRESET

### ISSUE THREAD

**Issue by lhagerdon** [PipedreamHQ/pipedream#5155] opened 2023-01-11 02:47 UTC
**Describe the bug**
 Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (internal/errors.js:412:5)
    at __node_internal_errnoException (internal/errors.js:542:12)
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)

**To Reproduce**
1. Add trigger.
2. Send data to webhook.
3. Once data is sent, trying to run any Python code receives this error.

**Expected behavior**
When running the Hello, World! code, I expect to see "Hello, World!" printed out.

**Screenshots**
Error:

<img width="685" alt="image" src="https://user-images.githubusercontent.com/44867802/211706232-2bce9552-1520-418b-bbaa-a0518b9048c1.png">

Before webhook data is received:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/44867802/211706015-9dab57cc-8424-4e69-85d2-adee770b7ea3.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 108.0.1462.76

**Smartphone (please complete the following information):**

**Additional context**
Problem only begins occurring when webhook data is received. If new trigger is created, and no data has been received, I am able to run python code without any issues.

**Comment by DilanAthukorala** [comment] 2023-01-11 17:33
@lhagerdon  I am not able to recreate this issue, could you try to do a hard refresh `Chrome: Ctrl + Shift + R (PC) / Cmd + Shift + R (Mac)` and see if this is still observed.

**Comment by dmathukorala** [comment] 2023-01-11 20:08
@lhagerdon Noted, I will add this to our backlog for the dev team to investigate.

**Comment by ctrlaltdylan** [comment] 2023-01-17 14:26
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/5086

Please add to this existing issue instead.

**Closed by ctrlaltdylan** 2023-01-17 14:26 UTC
Labels: bug, question, triaged, tracked internally
