### ISSUE TITLE
Random ECONNRESET Error

### ISSUE THREAD

**Issue by GiladL-IVLead** [PipedreamHQ/pipedream#5572] opened 2023-02-27 08:19 UTC
I have a code that makes an api request to hubspot.
It keeps returning this error:

Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (internal/errors.js:412:5)
    at __node_internal_errnoException (internal/errors.js:542:12)
    at Pipe.onStreamRead (internal/stream_base_commons.js:209:20)
    
    This is the code:
    
![image](https://user-images.githubusercontent.com/126453917/221510378-c67f3cf3-df33-4106-9349-2aba9ab45c17.png)

**Comment by vunguyenhung** [comment] 2023-02-27 08:29
Hello @GiladL-IVLead, 

We apologize for the inconveniences! This is a known issue of Python code step that the Pipedream team is actively working on. Could you copy & paste your Python code into [the Github issue here](https://github.com/PipedreamHQ/pipedream/issues/5086) so that you the Pipedream team can help?

**Comment by GiladL-IVLead** [comment] 2023-02-27 08:44
I put it there.
no, line 29 returns info just fine, it worked before it randomly started returning the error

**Comment by ctrlaltdylan** [comment] 2023-02-27 15:26
Closing because this is a duplicate of https://github.com/PipedreamHQ/pipedream/issues/5086

@GiladL-IVLead please provide the code sample in text form on that issue so we can reproduce the bug and fix it! Thanks.

**Closed by ctrlaltdylan** 2023-02-27 15:26 UTC
Labels: question

**Comment by GiladL-IVLead** [comment] 2023-03-01 10:09
this isn't completed though, the while workflow doens't work and no matter what code I put there it returns an error...
