### ISSUE TITLE
[BUG] Inconsistency when runnig `this.$emit(event, metadata)` with property `id` in `metadata` object

### ISSUE THREAD

**Issue by jcortes** [PipedreamHQ/pipedream#1842] opened 2021-10-26 21:34 UTC
**Describe the bug**
There is a conflict when emitting an event in `dedupe: unique` strategy when a property `id` is included in the `metadata` object. Eg.
```
const id = Math.floor(Math.random() * 5);
const summaryRand = Math.floor(Math.random() * 100);
const summary = `test ${summaryRand}`;
const event = {
 id,
 summary,
};
const metadata = {
 id: JSON.strinfigy(event),
 summary,
 ts: Date.now(),
};
this.$event(event, metadata);
```

So after a while the events wont get emitted because seems like what matters here is the internal `id` in the metadata object.

**To Reproduce**
1. Create your own event source component:
2. Run the cli with `pd dev my-source-component.mjs`
3. Run the source manually from UI
4. Start looking at the logs

**Expected behavior**
Even if an `id` is included in the metadata, the hash value should be unique setting their own `id` Eg.
```
const metadata = {
 id: JSON.strinfigy(event), // event with id
 summary,
 ts: Date.now(),
};
```

**Workaround**
So the way to fix this from the component is not to include the `id` property in the `metadata` object something like
```
generateMeta(event) {
      const {
        // eslint-disable-next-line no-unused-vars
        id,
        ...otherProperties
      } = event;

      return {
        id: JSON.stringify(otherProperties),
        summary: `Testing`,
        ts: Date.now(),
      };
    },
```

**Comment by dylburger** [comment] 2021-11-24 01:47
@jcortes Can you remind me what the specific bug is here? i.e. what is the specific issue including the `id` in the event metadata with the `unique` dedupe strategy?

**Comment by jcortes** [comment] 2021-11-25 20:27
Yeah sure, I don't quite remember the component I was testing but as I was running the `source` component suddenlly I stop getting logs in the events tab from the UI and that was because I was sending the `id` property in the `metadata` object so as soon as I removed the `id` property from that object I started to see the events being loggout in the UI again

**Comment by dylburger** [comment] 2022-02-22 06:51
@jcortes could this be related to some of the other bugs we saw re: logs not showing up in the UI? Are you still able to reproduce?

**Comment by dylburger** [comment] 2022-03-01 23:23
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2022-03-01 23:23 UTC
Labels: bug, question, trigger / source
