### ISSUE TITLE
[BUG] Dialogflow - Detect Intent (the "path" argument is undefined)

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3472] opened 2022-07-19 14:22 UTC
**Describe the bug**

As a user, I'm unable to use the **Dialogflow - Detect Intent** pre-built action. Even with static query text, an error appears:

```
The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

![](https://files.slack.com/files-pri/TMZFXGSBF-F03Q347PEQ2/image.png)

**To Reproduce**
1. Create a new workflow
2. Add a Dialogflow - Detect Intent action
3. Define a **Query Input** that includes a `text` key and value

**Expected behavior**
I expect a Dialogflow detect intent API to be made with the provided query input.

**Screenshots**

![CleanShot 2022-07-19 at 10 22 31](https://user-images.githubusercontent.com/2694734/179773968-9dcf0cf0-9009-4513-8979-abb6ac627360.png)

**Additional context**
Slack post: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1657131166677999

**Comment by vunguyenhung** [comment] 2022-07-19 15:24
Hello @ctrlaltdylan, I can reproduce this issue on my side
![FireShot Capture 370 - Pipedream - Connect APIs, Remarkably Fast - pipedream com](https://user-images.githubusercontent.com/18277920/179788047-fd1f70f5-98cc-42cd-bd02-cea6d7a4cf25.png)

I will add this to our Component backlog 🙏

**Comment by feyzullah** [comment] 2022-07-28 14:35
Hi @vunguyenhung, I am about to open a PR for this. The issue is going to be resolved.
However there is something with the inputs. As the [doc link](https://googleapis.dev/nodejs/dialogflow/latest/google.cloud.dialogflow.v2beta1.IQueryInput.html) in `Query Input` prop states, it should have a text object(not string) and that objects requires a language code too. For example, `{"text": "hi what are you doing", "languageCode": "en-EN"}` is a good example for `text` field in `Query Input` object.
As I guess that prop cannot be understood well. What would be your suggestion to improve user friendliness here?

**Comment by vunguyenhung** [comment] 2022-07-28 14:51
Thank you for resolving this issue @feyzullah! I think for the `Query Input`, we can have it as object, and we can add a JSON example to the prop description. For example:
```
Query Input property. For example, `{"text": "hi what are you doing", "languageCode": "en-EN"}`. See [Query Input API Doc](https://googleapis.dev/nodejs/dialogflow/latest/google.cloud.dialogflow.v2beta1.IQueryInput.html)
```

**Comment by feyzullah** [comment] 2022-07-28 15:18
Hi @vunguyenhung, thank you very much for the suggestion. Is the following ok? What do you think?
![image](https://user-images.githubusercontent.com/8221369/181574866-55dcd5e6-8ecf-4f89-ac4e-43925f324116.png)

**Comment by vunguyenhung** [comment] 2022-07-28 15:19
@feyzullah seems OK to me! I think we can go ahead with this!

**Closed** 2022-07-29 16:55 UTC
Labels: bug, triaged
