### ISSUE TITLE
Charles Schwab api

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12529] opened 2024-06-22 07:47 UTC
### App
Charles Schwab api
https://developer.schwab.com/user-guides/apis-and-apps/test-in-sandbox

### Sources
webhooks from charts for trading

### Actions
api actions for buy, sell etc

**Comment by sergio-eliot-rodriguez** [comment] 2024-06-22 16:28
Duplicate of #11887

**Closed by sergio-eliot-rodriguez** 2024-06-22 16:28 UTC
Labels: app, trigger / source, user request, actions
