### ISSUE TITLE
[BUG] Pipedream Workflow UI - Last Event filter does not show last event date of the workflow

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6014] opened 2023-04-13 07:12 UTC
**Describe the bug**
Pipedream Workflow UI - Last Event filter does not show last event date of the workflow, and we can not sort workflow by last event

**To Reproduce**
1. Access [Pipedream workflows page](https://pipedream.com/workflows)
2. Create 2 new workflows with HTTP trigger, then generate test events for them
![image](https://user-images.githubusercontent.com/18277920/231681190-1b727de3-0151-43f2-9cec-8c14e3f9e0af.png)
![image](https://user-images.githubusercontent.com/18277920/231681208-19e2d114-38d5-4b03-ba79-17d26bd05cc6.png)
3. On Pipedream workflows page, sort the workflow by Last Event, observed that there's no last event information showing for those 2 workflows
![image](https://user-images.githubusercontent.com/18277920/231681710-1a2d48ba-229f-4606-967a-f80b84834c32.png)
4. Try to sort the workflow by last event is not working either

**Expected behavior**
The Last Event column should show correct information, and we should be able to sort the workflows by that column

**Additional context**
First reported by a user here: https://pipedream.com/community/t/bug-cannot-see-workflows-by-last-event/5533

**Comment by dylburger** [comment] 2023-07-31 04:30
Duplicate of #4568

**Closed by dylburger** 2023-07-31 04:30 UTC
Labels: bug, triaged, tracked internally
