### ISSUE TITLE
[Components] microsoft_advertising

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11001] opened 2024-03-15 16:34 UTC
# microsoft_advertising
## URLs
- https://learn.microsoft.com/en-us/advertising/
#### Prompt
Adds a contact to an already created customer list in Microsoft Ads. The required props to be configured include the customer list ID and the contact details.
#### URLs
- https://learn.microsoft.com/en-us/advertising/guides/
- https://learn.microsoft.com/en-us/advertising/guides/get-started/
- https://learn.microsoft.com/en-us/advertising/guides/reference/
- https://learn.microsoft.com/en-us/advertising/shopping-content/get-started/
- https://learn.microsoft.com/en-us/advertising/shopping-content/reference/
- https://learn.microsoft.com/en-us/advertising/hotel-service/get-started/
- https://learn.microsoft.com/en-us/advertising/hotel-service/reference/
- https://learn.microsoft.com/en-us/advertising/scripts/get-started/
- https://learn.microsoft.com/en-us/advertising/scripts/reference-overview/
- https://learn.microsoft.com/en-us/advertising/guides/get-started
- https://learn.microsoft.com/en-us/advertising/guides/authentication-oauth
- https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions
- https://learn.microsoft.com/en-us/advertising/guides/reports
- https://learn.microsoft.com/en-us/advertising/guides/sandbox
- https://learn.microsoft.com/en-us/advertising/guides/client-libraries
- https://learn.microsoft.com/en-us/advertising/shopping-content/get-started
- https://learn.microsoft.com/en-us/advertising/shopping-content/manage-products
- https://learn.microsoft.com/en-us/advertising/shopping-content/manage-product-pricing
- https://learn.microsoft.com/en-us/advertising/shopping-content/how-get-status-product-offers
- https://learn.microsoft.com/en-us/advertising/hotel-service/get-started
- https://learn.microsoft.com/en-us/advertising/hotel-service/manage-hotel-campaigns
- https://learn.microsoft.com/en-us/advertising/hotel-service/reporting
- https://learn.microsoft.com/en-us/advertising/hotel-service/code-examples
- https://learn.microsoft.com/en-us/advertising/transaction-message/transaction-message
- https://learn.microsoft.com/en-us/advertising/hotel-feed/hotel-feed
- https://learn.microsoft.com/en-us/advertising/pos-feed/pos-feed
- https://learn.microsoft.com/en-us/advertising/scripts/get-started
- https://learn.microsoft.com/en-us/advertising/scripts/concepts/authorization
- https://learn.microsoft.com/en-us/advertising/scripts/guides/single-account-access
- https://learn.microsoft.com/en-us/advertising/scripts/guides/multi-account-access
- https://learn.microsoft.com/en-us/advertising/scripts/examples/
- https://learn.microsoft.com/en-us/advertising/scripts/reference-overview
#### Prompt
Removes a contact from an existing customer list in Microsoft Ads. The required props include the ID of the customer list from which the contact is to be removed, along with the contact's identifying details.
#### URLs
- https://learn.microsoft.com/en-us/advertising/guides/authentication-oauth
- https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions
- https://learn.microsoft.com/en-us/advertising/guides/campaign-management-guides
- https://learn.microsoft.com/en-us/advertising/guides/client-libraries
- https://learn.microsoft.com/en-us/advertising/scripts/concepts/authorization
- https://learn.microsoft.com/en-us/advertising/scripts/guides/single-account-access
- https://learn.microsoft.com/en-us/advertising/scripts/guides/multi-account-access
#### Prompt
Creates a new customer list in Microsoft Ads. The required props are the basic information such as the name and description of the customer list to be created.
#### URLs
- https://learn.microsoft.com/en-us/advertising/guides/get-started
- https://learn.microsoft.com/en-us/advertising/guides/authentication-oauth
- https://learn.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions
- https://learn.microsoft.com/en-us/advertising/guides/campaign-management-guides
- https://learn.microsoft.com/en-us/advertising/guides/reports
- https://learn.microsoft.com/en-us/advertising/guides/sandbox
- https://learn.microsoft.com/en-us/advertising/guides/client-libraries
- https://learn.microsoft.com/en-us/advertising/guides/concepts
- https://learn.microsoft.com/en-us/advertising/shopping-content/get-started
- https://learn.microsoft.com/en-us/advertising/shopping-content/manage-products
- https://learn.microsoft.com/en-us/advertising/shopping-content/manage-catalogs
- https://learn.microsoft.com/en-us/advertising/shopping-content/how-get-status-product-offers
- https://learn.microsoft.com/en-us/advertising/shopping-content/manage-product-pricing
- https://learn.microsoft.com/en-us/advertising/shopping-content/code-examples
- https://learn.microsoft.com/en-us/advertising/shopping-content/reference
- https://learn.microsoft.com/en-us/advertising/hotel-service/get-started
- https://learn.microsoft.com/en-us/advertising/hotel-service/manage-hotel-campaigns
- https://learn.microsoft.com/en-us/advertising/hotel-service/reporting
- https://learn.microsoft.com/en-us/advertising/transaction-message/transaction-message
- https://learn.microsoft.com/en-us/advertising/hotel-feed/hotel-feed
- https://learn.microsoft.com/en-us/advertising/pos-feed/pos-feed
- https://learn.microsoft.com/en-us/advertising/hotel-service/code-examples
- https://learn.microsoft.com/en-us/advertising/hotel-service/reference
- https://learn.microsoft.com/en-us/advertising/scripts/get-started
- https://learn.microsoft.com/en-us/advertising/scripts/concepts/authorization
- https://learn.microsoft.com/en-us/advertising/scripts/guides/single-account-access
- https://learn.microsoft.com/en-us/advertising/scripts/guides/multi-account-access
- https://learn.microsoft.com/en-us/advertising/scripts/examples/
- https://learn.microsoft.com/en-us/advertising/scripts/reference-overview

**Comment by michelle0927** [comment] 2024-12-13 18:48
Duplicate of #10869

**Closed by michelle0927** 2024-12-13 18:48 UTC
Labels: triaged
