### ISSUE TITLE
[APP] Cloudmersive.com 

### ISSUE THREAD

**Issue by sjn001tvh** [PipedreamHQ/pipedream#1320] opened 2021-06-14 00:13 UTC
I might have requested this before, but they have a api calls to convert certain file types of a different file type.  The one I'm specifically interested in is the conversion api call for an xlsx file format to a csv format.  Thanks, Scott.

**Comment by dylburger** [comment] 2021-08-14 03:44
Duplicate of #1290

**Closed by dylburger** 2021-08-14 03:44 UTC
