### ISSUE TITLE
[FEATURE] Share components between GitLab --> Gitlab (Developer App)

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#11547] opened 2024-04-18 16:38 UTC
We've added a new GitLab (Developer App) that enables users who are using self-hosted GitLab to be able to connect using their own application. 

Can the components that are currently available within GitLab be shared with the new GitLab (Developer App)?

**Comment by GTFalcao** [comment] 2024-04-23 21:07
@vunguyenhung the Project ID prop lists [user's owned projects](https://docs.gitlab.com/ee/api/projects.html#list-user-projects) instead of listing [all projects visible to the user](https://docs.gitlab.com/ee/api/projects.html#list-all-projects). If this should be changed, we should change it in the original Gitlab app. I was also able to list several projects on my account using the latter endpoint, but had zero returned using the former.

I fixed the error preventing sources from being used. I also double checked that all propDefinitions are being correctly imported from the original Gitlab app and assigned to the new one, so the code being executed is exactly the same (as it should be, since the API is the same)

**Comment by GTFalcao** [comment] 2024-04-24 13:20
I've adjusted the List Projects behavior. Note that since the behavior is the same in both apps, I've adjusted the original Gitlab app to match the desired behavior, so all Gitlab components are now being updated as well.

The 403 issue when listing epics also happens in the existing Gitlab app, unrelated to the component migration - [the documentation mentions the Epics API as a premium+ feature,](https://docs.gitlab.com/ee/api/epics.html) unavailable to the free tier.

**Comment by GTFalcao** [comment] 2024-04-25 02:22
@vunguyenhung just remembered, perhaps the Epic ID prop's description should mention this premium tier limitation?

**Comment by GTFalcao** [comment] 2024-04-30 06:30
Hey @vunguyenhung , thanks for the very thorough testing, this is an overview of all the components that had issues in your report:
- Create Epic
    - ✅ Marked Parent ID as optional
    - ✅ Fixed the Label prop
    - ❓  The Parent ID prop seems to be sent properly, this might need some business rule understanding to figure out
- ✅ Update Epic: labels prop was fixed, I could not reproduce 'hang at loading' issue, could it be intermittent?
- ✅ Update Issue: fixed labels prop not being sent in request
- ❓ New Issue: I could not reproduce the error, I'm getting events emitted normally and no errors logged - could it happen only in some scenarios? (the expected schema seems to be correct, too)
- ❓ New Merge Request: same as above
- ✅ New Mention: this happened due to the username prop being optional but the source used it to filter mentions. I changed the prop to required
- ✅ New Milestone: fixed the bug
- ✅ New Review Request: adjusted behavior to check 'reviewers' instead of 'assignees', and received events as expected, I could not reproduce the console error, might be situational?

Since all of these issues happen in the current (live) Gitlab components, I think any pending ones that need further investigation or business rule understanding, should be moved to a new issue so we can release all the fixes and improvements already done (as well as adding the components to the Gitlab Developer App).

Let me know if this makes sense.

**Comment by GTFalcao** [comment] 2024-05-03 18:27
It seems "Group ID" and "Group Path" were mixed, which was causing the issues in the group labels and other props that depended on the group id (but received a group path). I also added an error treatment for the merge request sources.

**Closed** 2024-05-06 15:42 UTC
Labels: enhancement, triaged

**Comment by malexanderlim** [comment] 2024-05-06 18:11
Big thank you @GTFalcao for the close attention to detail on these component, as well as to @vunguyenhung for the thorough testing here - really happy to see the usability improvements on these GitLab components!
