### ISSUE TITLE
[Components] affinity

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#13189] opened 2024-08-07 23:53 UTC
# affinity
#### Prompt
Emits new event when a new organization is created. No additional props required.
#### Prompt
Emit new event when a new opportunity is created. Requires 'opportunity name' prop and 'opportunity owner' prop can be optionally added.
#### Prompt
Emit new event when a new person is added. Requires 'person name' prop and optional 'email' and 'phone number' props.
#### Prompt
Creates a new person entry within Affinity. It requires a prop 'name' and optional 'email_address' prop. 'Search' prop can be used if duplicates are to be avoided.
#### Prompt
Updates fields for an existing entry, this can be a person, organization, or opportunity. Requires 'entity_id' and 'fields_to_update' props to be specified.
#### Prompt
Finds an opportunity by its name or creates a new one if it does not exist. This requires the 'name' prop. New opportunities created will prevent duplicate entries.

**Comment by michelle0927** [comment] 2024-10-29 20:32
Requires scheduling a demo.

**Comment by michelle0927** [comment] 2024-12-14 22:08
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/3542

**Closed by michelle0927** 2024-12-14 22:08 UTC
Labels: blocked, triaged
