### ISSUE TITLE
[ENHANCMENT] Improve Pipedream app search

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6992] opened 2023-06-22 06:55 UTC
**Is your feature request related to a problem? Please describe.**
When I search for `Google Ads` app on the step section, the search results show other Google apps first before the Google Ads app
<img width="914" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/b35f1c10-c979-4cba-905d-be896e01ccc2">

I will need to tap "Load More Apps" a few times then scroll down then I see the `Google Ads`
<img width="928" alt="Screenshot 2023-06-22 at 13 28 24" src="https://github.com/PipedreamHQ/pipedream/assets/18277920/7cb64272-a125-4d2e-949e-7a6f7e5de0ba">

**Describe the solution you'd like**
Make the App search more accurate, so when I search `Google Ads`, the Google Ads app should appear first, then other apps that having Google or Ads keyword

**Do you have a workaround?**
No

**Additional context**
Raised by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1687413632976739?thread_ts=1687314031.268139&cid=CPTJYRY5A

**Comment by dylburger** [comment] 2023-06-23 03:37
This has the same root cause as #661, closing since we're tracking that one internally, as well.

**Closed by dylburger** 2023-06-23 03:37 UTC
Labels: enhancement, triaged, tracked internally
