### ISSUE TITLE
[BUG] Workflow event show incorrect status

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#6509] opened 2023-05-16 07:26 UTC
**Describe the bug**
Some events in the workflow always show In Progress status, even though the events are emitted a long time ago
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/5a68b543-5986-4d4b-ba78-0126bea24c34)

Please refer to this workflow: https://pipedream.com/@tmog/cu-rhm-services-p_JZCYDdZ/inspect

**Expected behavior**
The events should show status correctly

**Additional context**
Reported by customers here:
- https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1684221439909369
- https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1681984975381659

**Comment by dylburger** [comment] 2023-07-31 01:26
We believe we've isolated the cause of these issues. I'm closing here and we can re-open if we get other reports.

**Closed by dylburger** 2023-07-31 01:26 UTC
Labels: bug, triaged, tracked internally
