### ISSUE TITLE
[BUG]  SendInBlue Add or update contact Action

### ISSUE THREAD

**Issue by TomVonWood** [PipedreamHQ/pipedream#4482] opened 2022-10-12 10:45 UTC
**Describe the bug**
I’ve been trying to use the sendinblue add or update contact step (action). I keep seeing a Request failed with status code 404 error with status text ‘Not Found’. It appears as if it tries to update even though no contact can be found while it should then create a new entry. 

**To Reproduce**
Add a new contact (not already in the list) to send in blue with the add or update step

**Expected behavior**
Check if a contact is already in the list, if yes update it with new details, if no create a new entry in the email list. 

**Screenshots**
<img width="897" alt="image" src="https://user-images.githubusercontent.com/115629329/195323052-87758871-b916-4490-84af-c52bba2e833d.png">

**Desktop (please complete the following information):**
 - OS: 12.1
 - Browser chrome 105.0.5195.125

**Additional context**
` at null.createError (/tmp/__pdg__/dist/code/930cdb1180385f562a3fda17a9eae989453996d504386b496b5bccb3542c630b/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/createError.js:16:15)
    at null.settle (/tmp/__pdg__/dist/code/930cdb1180385f562a3fda17a9eae989453996d504386b496b5bccb3542c630b/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/tmp/__pdg__/dist/code/930cdb1180385f562a3fda17a9eae989453996d504386b496b5bccb3542c630b/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at null.endReadableNT (internal/streams/readable.js:1333:12)
    at process.processTicksAndRejections (internal/process/task_queues.js:82:21)`

**Comment by vunguyenhung** [comment] 2022-10-12 15:19
Hello @TomVonWood, I couldn't reproduce your issue with the following cases:

Having the `Contact` prop empty, so that the action will create a new contact
![2213 - 1210](https://user-images.githubusercontent.com/18277920/195381204-ed3e0545-60ee-412c-bd2e-929fcd6f46b7.png)

Having the `Contact` prop set, so that the action will update existing contact
![2214 - 1210](https://user-images.githubusercontent.com/18277920/195381531-ec8f15b8-0f20-4d09-8037-7cd6e2f5635d.png)


Would you mind sharing your action's configuration in order for me to help?

**Comment by TomVonWood** [comment] 2022-10-17 13:04
Hi @vunguyenhung! Thanks for helping out. I think the problem lies in the last remaining case. When the contact field is filled out but the supplied email is not yet in our lists. I believe in that case it should create a new contact but it does not do that and instead gives me a 404. 

![image](https://user-images.githubusercontent.com/115629329/196184451-255bc1c0-ff25-41c2-8759-393f734c401c.png)
![image](https://user-images.githubusercontent.com/115629329/196184461-edfa9c2a-b90c-4749-80b4-fb28b1744a17.png)

Hope this helps

**Comment by TomVonWood** [comment] 2022-10-17 13:05
Before this step I fetch the contact details from a webflow form

**Comment by vunguyenhung** [comment] 2022-10-17 13:44
Hello @TomVonWood, I'm not quite understand your images, as it is not showing SendInBlue - Add or update contact action. Would you mind sharing your SendInBlue action configuration if possible?

**Comment by TomVonWood** [comment] 2022-10-17 13:51
Ah sorry I must have accidentally uploaded the same image twice. Here is two new images. 
![image](https://user-images.githubusercontent.com/115629329/196194587-82feaaed-e5a9-4894-a213-6c3f58ebb1a7.png)

![image](https://user-images.githubusercontent.com/115629329/196194865-8bda54f2-0a4d-4892-b5e8-0bb21dc2a958.png)

**Comment by vunguyenhung** [comment] 2022-10-18 00:41
Hello @TomVonWood, would you mind providing the sample data from `steps.trigger.event`? I suspect that some of the field might be missing, or incorrectly passed in

**Comment by TomVonWood** [comment] 2022-10-18 07:20
@vunguyenhung Here it is.

 <img width="893" alt="image" src="https://user-images.githubusercontent.com/115629329/196362543-3cdacd69-e4e4-4451-a96a-7c83bf195ef7.png">
 
 And here are some pictures from the SIB config. 
<img width="891" alt="image" src="https://user-images.githubusercontent.com/115629329/196362867-310a000d-0626-4c11-a88a-5469f5edb46d.png">
<img width="892" alt="image" src="https://user-images.githubusercontent.com/115629329/196362927-fa0991c5-5910-455b-b5c5-e886c628f468.png">
<img width="891" alt="image" src="https://user-images.githubusercontent.com/115629329/196362961-dfa40233-3d8f-4026-9243-af1e07b2130b.png">

**Comment by vunguyenhung** [comment] 2022-10-18 13:56
Hello @TomVonWood, apologize for the late response. I'm able to reproduce your issue using your data.
![2053 - 1810](https://user-images.githubusercontent.com/18277920/196449557-b4d5da7b-5222-45f2-a7be-a84660835c8c.jpg)

To add a new contact, you should have the `Contact` prop **empty**. Then after you have emptied your `Contact` prop, you would likely to face a new error `Invalid email address`
![2054 - 1810](https://user-images.githubusercontent.com/18277920/196449817-f1cabe7d-2b9e-449c-b109-ac250607aed5.jpg)

This is because your test email might be invalid per SendInBlue validation. So you should change your test email so that SendInBlue won't complain. For example,
![2051 - 1810](https://user-images.githubusercontent.com/18277920/196449187-61fd2e2a-b937-4af1-aa61-16e73325e0a4.jpg)

**Comment by TomVonWood** [comment] 2022-10-18 15:06
@vunguyenhung Thanks for looking into the issue. So if I understand correctly. If I want to have it behave as described in the description of the step: Email, If not present the email will be inserted,  it (which i'm assuming refers to contact) will be used to search the contact, if it can be found the contact will be updated else it will be added. Then I should leave the contact field empty? When I do that it will not duplicate a contact if it is already present in the list?

When I do that now with my test data I do get the error you describe. What must I do to ensure that the data is valid per sendinblue verification as you describe? The email I'm testing with in this case is a reachable email address of one of our customers which was already added to our lists.

**Comment by vunguyenhung** [comment] 2022-10-18 16:13
@TomVonWood if there's already an email on the list, SendInBlue will send back a duplicated email error (you can try it by executing the action with valid data twice). So putting into the context, if a user input the form with the same email adress twice, the workflow will execute successfully on the first time (and add a new contact as a result), then failed on the second time as there's already an existing contact with the same email.

For the email format that SendInBlue treat as invalid: unfortunately, on Pipedream side we couldn't do anything to workaround it. I think SendInBlue support should be able to explain to you why the email is treated as invalid, and maybe they can suggest a workaround for it.

**Comment by TomVonWood** [comment] 2022-10-19 08:20
@vunguyenhung Problem is this is an example of a contact that was already in the list (added by pipedream automation). Hence it seems to not be updating or duplicating the contact but instead giving me a 400 error as a bad request. So it does seem to be on Pipedream's end here.

**Comment by vunguyenhung** [comment] 2022-10-19 11:23
Hello @TomVonWood, I would suggest that you split the Create contact case with Update contact case to avoid confusion. For example, you can have one workflow to Create Contact with a specific setting, and another workflow to Update Contact with a specific setting. Similarly, you can have 2 forms to allow create & update contact.

**Comment by TomVonWood** [comment] 2022-10-19 15:06
@vunguyenhung I'm afraid it is not really an option for me to run 2 forms as they are customer facing and it would complicate things too much. However, I guess I could run two workflows of which one will error.

Is this a confirmed bug now? If so I would like to be kept up to date on the progress made fixing this error. Surely this is all not expected behaviour.

**Comment by vunguyenhung** [comment] 2022-10-19 15:28
@TomVonWood glad to know that you have a workaround for now. 

For the bug, I afraid this is not a confirmed bug on Pipedream side. As the Pipedream action passed your data (email, sms, First name, Last name, etc...) to SendInBlue correctly. SendInBlue indeed received the data, but decided to send back error due to data validation failed. Pipedream's role in this case is just passing the error to you for you to fix the data, or requesting SendInBlue support to by pass the data validation somehow. On Pipedream side, we can not fix error from SendInBlue.

**Comment by dylburger** [comment] 2022-10-26 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2022-10-26 23:29 UTC
Labels: bug, question
