### ISSUE TITLE
Open Assistance 

### ISSUE THREAD

**Issue by sanjeetarya001** [PipedreamHQ/pipedream#7433] opened 2023-07-29 16:18 UTC
[](https://open-assistant.io/)
Conversational AI for everyone. An open-source project to create a chat-enabled GPT LLM run by LAION and contributors worldwide.

This is very similar to OpenAI ChatGPT

Please add this, It will be a great help.

**Comment by dylburger** [comment] 2023-07-30 20:13
Closing since this is a duplicate of #7437 and that has the link to the API docs — thanks for submitting that.

**Closed by dylburger** 2023-07-30 20:13 UTC
Labels: enhancement, app
