### ISSUE TITLE
[Components] neuronwriter

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12039] opened 2024-05-21 22:35 UTC
# neuronwriter
## URLs
- https://contadu.crisp.help/en/article/neuronwriter-api-how-to-use-2ds6hx/?bust=1715936854339
#### Prompt
Emit new event when a project has to be selected. This trigger requires the user to configure 'project id' prop, which identifies the project to be retrieved.
#### URLs
- https://contadu.crisp.help/en/article/contadu-api-how-to-use-1q4bt49/
- https://contadu.crisp.help/en/article/neuronwriter-api-how-to-use-2ds6hx/?bust=1715936854339
#### Prompt
Emit new event once the NeuronWriter API has processed your query and the recommendations are ready. Props required for this trigger include the 'query id' and optional props could include 'quality' and 'style' of recommendation.
#### URLs
- https://contadu.crisp.help/en/article/neuronwriter-api-how-to-use-2ds6hx/?bust=1715936854339
- https://contadu.crisp.help/en/article/contadu-api-how-to-use-1q4bt49/
#### Prompt
Emit new event when a user's query has been marked as 'Done', indicating that the content is ready for publication. Required prop for this trigger is 'query id'. An optional prop might be the 'publish destination'.
#### URLs
- https://contadu.crisp.help/en/article/contadu-api-how-to-use-1q4bt49/
- https://contadu.crisp.help/en/article/neuronwriter-api-how-to-use-2ds6hx/
#### Prompt
Retrieves the details of a given query. The required props are the 'query id'. The optional prop is 'status'. If the 'status' prop is set to 'ready', it means your query has been processed and the recommendations for your query are already available.
#### URLs
- https://contadu.crisp.help/en/article/contadu-api-how-to-use-1q4bt49/
- https://contadu.crisp.help/en/article/neuronwriter-api-how-to-use-2ds6hx/?bust=1715936854339
#### Prompt
Fetches the latest content revision that has been saved for a particular query. Required props are the 'query id'. No optional props for this action.
#### URLs
- https://contadu.crisp.help/en/article/neuronwriter-api-how-to-use-2ds6hx/?bust=1715936854339
- https://contadu.crisp.help/en/article/contadu-api-how-to-use-1q4bt49/
#### Prompt
Produces a new query record based on a specific keyword, plus a search engine and language. Once the NeuronWriter completes the analysis, which typically takes around 60 seconds, it produces recommendations for writing SEO-optimized content. The required props are 'keyword', 'search engine', and 'language'. No optional props for this action.
#### URLs
- https://contadu.crisp.help/en/article/contadu-api-how-to-use-1q4bt49/
- https://contadu.crisp.help/en/article/neuronwriter-api-how-to-use-2ds6hx/?bust=1715936854339

**Comment by michelle0927** [comment] 2024-05-29 16:44
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/12067

**Closed by michelle0927** 2024-05-29 16:44 UTC
Labels: triaged
