### ISSUE TITLE
[FEATURE] Allow access to trigger parameters

### ISSUE THREAD

**Issue by cfjedimaster** [PipedreamHQ/pipedream#247] opened 2020-07-11 17:51 UTC
**Is your feature request related to a problem? Please describe.**
Steps should be able to access the configuration information of a trigger/event source.

**Describe the solution you'd like**
Basically what I just said. ;) As a practical example, in the RSS event source, I'd like to be able to know the RSS url that was checked.

**Do you have a workaround?**
Nope.

**Comment by dylburger** [comment] 2020-12-10 00:38
Duplicate of #592

**Closed by dylburger** 2020-12-10 00:38 UTC
Labels: enhancement
