### ISSUE TITLE
[BUG] New Row Added (Instant) from Google Sheets spams duplicated rows

### ISSUE THREAD

**Issue by rose111data** [PipedreamHQ/pipedream#4808] opened 2022-11-22 20:41 UTC
**Describe the bug**
For any sheet connected to any endpoint, every row in the triggering sheet spams duplicate rows multiple times.

**To Reproduce**
1. New Row Added (Instant) from Google Sheets trigger
2. Configure trigger to any spreadsheet or worksheet on my account
3. Add any action 
4. Deploy

**Expected behavior**
New row is added in trigger sheet, action is performed once per triggering row

**Screenshots**

**Configuration:**
![Untitled design](https://user-images.githubusercontent.com/116825158/203415802-1da64769-15aa-472a-ac47-37ea29dd48a2.png)

**Result:**
![Screenshot (210)](https://user-images.githubusercontent.com/116825158/203415945-48aad587-05f9-4915-b219-73b5ccb8c8da.png)

**Desktop (please complete the following information):**
 - Windows
 - Firefox

**Additional context**
Was working great, stopped working very suddenly one day. Did not realize until I received an email that my invocations had been used up. :( Seems to do the same thing, regardless of the Workbook or Spreadsheet used for the trigger, or the destination as an endpoint.

**Comment by vunguyenhung** [comment] 2022-11-23 14:13
Hello @rose111data, I tried to reproduce your bug but couldn't. Here're the steps I've taken:

1. Create 5 test sheets
2. Create a Pipedream trigger - New Row Added (Instant), link to 5 test sheets
3. Added new rows on the test sheets
4. I observed that the events are emitted correctly
![21 10 33 - 23 - 11 - 2022](https://user-images.githubusercontent.com/18277920/203567768-d654ab8e-74db-40fc-ab85-ef7e75dfc0ad.png)

Would you mind providing more details of your sheet? Is there any formula that may modify the rows?

**Comment by rose111data** [comment] 2022-11-23 21:32
Sure, thank you!

I was afraid that may have been the issue. There are some columns that use concatenate upon a form submission; is that what's triggering it repeatedly?

**Comment by vunguyenhung** [comment] 2022-11-24 01:26
Hello @rose111data, I suspect the formula is the cause. Would you mind move the formula to another sheet and try again to see if the issue persist? 

If the formula is the case then it's quite hard for us on Pipedream side to do anything about it. Since we emit events when ever Google Sheet tells us there's a new row, so we depends on Google Sheet in this case

**Comment by js07** [comment] 2022-11-28 04:31
@vunguyenhung This appears to be an issue with the Google Sheets **New Row Added** sources when the last row in the sheet has cells with values. I created a [PR](https://github.com/PipedreamHQ/pipedream/pull/4835) to fix the issue.

**Comment by andrewjschuang** [comment] 2022-11-29 14:52
@js07 I'm thinking - if we iterate through all the rows and hash the row number with the row values, [in this line](https://github.com/PipedreamHQ/pipedream/blob/master/components/google_sheets/sources/common/new-row-added.mjs#L25) - so use `id = hash(rowNumber, rowValues)` - and emit all the rows with `dedupe = unique`,
Then rows that were already emitted will not be duplicated, and rows that were edited or are new will be emitted.

I'm thinking of this because I tested that - if you add or edit a row that is below the last row in the sheet with values, then it won't be emitted

**Comment by js07** [comment] 2022-11-29 20:22
@andrewjschuang Using a hash of the row number and row values to dedupe events sounds like a good idea.

> if you add or edit a row that is before the last row in the sheet with values, then it won't be emitted.

Currently, if you add a row to the sheet out of sequence, it looks like empty rows before the new row will also be emitted as events. So adding/editing a row that's before the last row with values doesn't cause another event to be emitted for that row.

**Comment by andrewjschuang** [comment] 2022-11-29 20:30
> Currently, if you add a row to the sheet out of sequence, it looks like empty rows before the new row will also be emitted as events. So adding/editing a row that's before the last row with values doesn't cause another event to be emitted for that row.

I didn't get events for rows added in the middle, only when adding a row after the previous last emitted row.

**Comment by js07** [comment] 2022-11-29 20:33
> I didn't get events for rows added in the middle, only when adding a row after the previous last emitted row.
Also when receiving an event, the only new emitted rows are the ones that are after the previous last emitted row.

I think that's (currently) intended. The description of the **New Row Added** source is "Emit new events each time a row or rows are added to the bottom of a spreadsheet in a shared drive".

**Comment by andrewjschuang** [comment] 2022-11-29 20:49
> I think that's (currently) intended. The description of the **New Row Added** source is "Emit new events each time a row or rows are added to the bottom of a spreadsheet".

Oh, sorry didn't read that. Thanks for clearing it up!

**Comment by rose111data** [comment] 2022-11-30 16:29
> Hello @rose111data, I suspect the formula is the cause. Would you mind move the formula to another sheet and try again to see if the issue persist?
> 
> If the formula is the case then it's quite hard for us on Pipedream side to do anything about it. Since we emit events when ever Google Sheet tells us there's a new row, so we depends on Google Sheet in this case

So sorry for the late reply - the formulas were TEXTJOINS or CONCATENATES. 

I did test a sheet with the same formula, and one without a formula. Upon a test form submission to both sheets, the same issue occurred. 

> @vunguyenhung This appears to be an issue with the Google Sheets **New Row Added** sources when the last row in the sheet has cells with values. I created a [PR](https://github.com/PipedreamHQ/pipedream/pull/4835) to fix the issue.

Thank you so much! I appreciate everyone's time.

**Comment by Hassan-Abbas-SQA** [comment] 2022-11-30 21:24
iam able to reproduce the bug @rose111data 
<img width="904" alt="image" src="https://user-images.githubusercontent.com/104946677/204911086-0ee3ea1a-2575-4503-b3e2-8a86c553fba0.png">

**Comment by rose111data** [comment] 2022-12-02 17:37
> iam able to reproduce the bug @rose111data 

I feel validated. 😄  Thank you!

**Comment by dylburger** [comment] 2022-12-09 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2022-12-09 23:29 UTC
Labels: bug, question, triaged

**Comment by Hassan-Abbas-SQA** [comment] 2022-12-14 16:57
works fine now @rose111data 
![image](https://user-images.githubusercontent.com/104946677/207658830-47146061-01cf-4110-b32b-1f0e9297e087.png)

**Comment by rose111data** [comment] 2022-12-15 22:13
I saw @Hassan-Abbas-SQA , thank you all so much!
