### ISSUE TITLE
[Components] rentcast

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12037] opened 2024-05-21 22:34 UTC
# rentcast
## URLs
- https://developers.rentcast.io/reference/introduction
#### Prompt
Fetches rental statistics and market trends based on a US zip code. Required prop is 'zip_code'.
#### URLs
- https://developers.rentcast.io/reference/search-queries
- https://developers.rentcast.io/reference/property-records
- https://developers.rentcast.io/reference/property-records-random
- https://developers.rentcast.io/reference/property-record-by-id
- https://developers.rentcast.io/reference/property-valuation
- https://developers.rentcast.io/reference/value-estimate
- https://developers.rentcast.io/reference/rent-estimate-long-term
- https://developers.rentcast.io/reference/property-listings
- https://developers.rentcast.io/reference/rental-listings-long-term
- https://developers.rentcast.io/reference/rental-listing-long-term-by-id
- https://developers.rentcast.io/reference/market-data
- https://developers.rentcast.io/reference/market-statistics
#### Prompt
Retrieves a specific property record based on a unique id. Required prop is 'id'. Use this action to find extensive details for a single property.
#### URLs
- https://developers.rentcast.io/reference/property-records
- https://developers.rentcast.io/reference/property-record-by-id
#### Prompt
Fetches a rent estimate, along with comparable properties. Required prop is 'property_id'. Use this action to determine the potential rent for a property.
#### URLs
- https://developers.rentcast.io/reference/property-data
- https://developers.rentcast.io/reference/property-records
- https://developers.rentcast.io/reference/property-records-random
- https://developers.rentcast.io/reference/property-record-by-id
- https://developers.rentcast.io/reference/property-valuation
- https://developers.rentcast.io/reference/value-estimate
- https://developers.rentcast.io/reference/rent-estimate-long-term
- https://developers.rentcast.io/reference/rental-listings-long-term
- https://developers.rentcast.io/reference/rental-listing-long-term-by-id

**Comment by michelle0927** [comment] 2024-05-29 16:47
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/12065

**Closed by michelle0927** 2024-05-29 16:48 UTC
Labels: triaged
