### ISSUE TITLE
[BUG] Data Store item cannot be deleted after transfer of ownership

### ISSUE THREAD

**Issue by aarontbt** [PipedreamHQ/pipedream#5679] opened 2023-03-10 16:06 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Data Store'
2. Click on '....' > Delete for 'ClickUp'
3. It tried to delete but end up in the same popup

**Expected behavior**
Data Store item 'ClickUp' was transfer from an individual account to workplace. The said item then cannot be deleted after that, it will try to do it but end up nothing happen.

**Screenshots**
<img width="1213" alt="Screenshot 2023-03-11 at 12 00 23 AM" src="https://user-images.githubusercontent.com/50138173/224363797-9c1982c5-8752-47fd-8710-f025454ba66c.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 13.2.1 (22D68)
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 110.0.5481.177 (Official Build) (arm64)

**Additional context**
Workplace: https://pipedream.com/@tmog

**Comment by Harmonygrams** [comment] 2023-03-12 15:29
I can fix this issue. Has it been assigned to anyone?

**Comment by dannyroosevelt** [comment] 2023-03-13 18:48
Thanks for flagging, @aarontbt -- I was able to reproduce the issue, and I'll get the team to check it out.

**Comment by dylburger** [comment] 2023-07-31 00:52
Duplicate of #3990

**Closed by dylburger** 2023-07-31 00:52 UTC
Labels: bug, triaged, tracked internally
