### ISSUE TITLE
[Components] bubble

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10664] opened 2024-03-01 00:50 UTC
# bubble
#### Prompt
Emit new event when a Bubble workflow including the plugin action is activated. No props required for this trigger.
#### Prompt
Emit new event when there is a new data thing of a given type. Required props: 'Type of Data Thing' to watch for.
#### Prompt
Emit new event when an event is posted from your Bubble application. No props required for this trigger.
#### Prompt
Create a new entity in Bubble. This action requires a 'thing' prop which is the entity to be created.
#### Prompt
Adjust an existing entity in Bubble by its ID. This action requires a 'thing-id' prop which is the ID of the entity to be modified.
#### Prompt
Locate a specific entity in the Bubble database. The action needs a 'search-parameter' prop which is the parameter to be used in searching for the entity.

**Comment by michelle0927** [comment] 2024-03-01 18:56
Paid account needed
<img width="895" alt="Screenshot 2024-03-01 at 1 53 14 PM" src="https://github.com/PipedreamHQ/pipedream/assets/10889229/09317599-151e-4408-b576-abbb2ae60a2e">

**Comment by michelle0927** [comment] 2024-11-13 22:55
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/13187

**Closed by michelle0927** 2024-11-13 22:55 UTC
Labels: blocked, triaged, paid-account-needed
