### ISSUE TITLE
[BUG] Files moved from one folder to another not detected by instant Google Drive source. 

### ISSUE THREAD

**Issue by jwagriff** [PipedreamHQ/pipedream#5411] opened 2023-02-06 08:53 UTC
**Describe the bug**
Dragging and dropping a file from one folder to a monitored folder via the Instant Google Drive files trigger does not trigger an event. 

**To Reproduce**
1. Move a file from one monitored folder to another
2. See error

**Expected behavior**
Ideally this would trigger an event.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 109.0.5414.119

**Additional context**
I use pipedream to automate a document proofing workflow, with two folders being monitored.

**Comment by vunguyenhung** [comment] 2023-02-06 15:07
Hello @jwagriff, 

I couldn't reproduce your issue, I tried the following steps:
1. I created the source Google Drive - New or Modified Files with the `Watch For Changes To File Properties` set to TRUE
![image](https://user-images.githubusercontent.com/18277920/217007176-7e9e7c94-0126-4fa1-8d51-a8fc03ccbaf0.png)
2. Then on Google Drive, I drag & drop files into a test folder
3. Finally, checking the Pipedream source, I can see new change events
![image](https://user-images.githubusercontent.com/18277920/217007529-4e44f237-22d0-49c3-90b0-da3e3450f325.png)

Would you mind sharing the Google Drive source that you're using? Also could you try to follow my reproduce steps to see if it serve your needs?

**Comment by jwagriff** [comment] 2023-02-07 11:59
Hi there @vunguyenhung.

Thank you for getting back to me. My workflow has two events. One sends out an email detailing that a file has been added to a "Proof Needed" folder, prompting my team's attention. The other is a "Proofed" folder, which does the same thing. 

Both of these workflows log data to a spreadsheet, which we use to track progress. Could your solution also do this? I wouldn't want it to send emails out for all files created in my google drive, only those added to specific folder.s

**Comment by jwagriff** [comment] 2023-02-07 11:59
S

**Comment by vunguyenhung** [comment] 2023-02-07 14:38
Hello @jwagriff, I think [Pipedream's filter actions](https://pipedream.com/docs/workflows/built-in-functions/#filter) might fit your need. You can define the filter action in one of your workflow so that it will only send emails when the event associated with a Google Drive folder

**Comment by jwagriff** [comment] 2023-02-08 08:34
Hi @vunguyenhung thank you for your help, that certainly sounds like it might work, but I can't seem to figure it out. I have made a test folder, added a file, and moved that file over to the test folder, but the only event generated is a file modification, and I'm not sure where I'd find the context of the folder being changed. Is this something you could help me with?

**Comment by dylburger** [comment] 2023-02-15 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2023-02-15 23:29 UTC
Labels: bug, question
