### ISSUE TITLE
Notion update_page do not accept ID stored in field from retrieve_page

### ISSUE THREAD

**Issue by tomnico76** [PipedreamHQ/pipedream#5004] opened 2022-12-20 17:59 UTC
**Describe the bug**
In previous steps I use retrieve page function to find ID of a Notion page. This ID is stored to  _steps.retrieve_page.$return_value.id_
If I use this  steps.retrieve_page.$return_value.id in update_page function in field Page ID I cannot assign anything to field Property Types. There is written "No matching options"

![image](https://user-images.githubusercontent.com/121122019/208733055-22ab998f-47de-4d1a-b6c9-28e4d64f3c30.png)

![image](https://user-images.githubusercontent.com/121122019/208734647-d41bed22-91fc-430e-b77e-4efb32606d78.png)

**To Reproduce**
1. create some trigger
2. Based on information from trigger use Notion retrieve_page
3. In Notion update_page enter variable from retrieve_page (for example steps.retrieve_page.$return_value.id)  in field Page ID .
4. Click on Property Names
5. You should see "No matching options"

**Expected behavior**
When I use the value 5b351efa-4b3d-48f0-a8a4-a2d70676020e of ID instead of variable steps.retrieve_page.$return_value.id I can see a drop down menu with fields of Notion page.

![image](https://user-images.githubusercontent.com/121122019/208733739-9c41cac2-93ca-4ee3-9e90-36e19e10a572.png)

**Desktop (please complete the following information):**
 - Windows 10 Home 22H2
 - Chrome  108.0.5359.125 (Oficiální sestavení) (64bitový)

**Comment by DilanAthukorala** [comment] 2022-12-21 17:03
@tomnico76 Thanks for reporting this issue, I am able to reproduce the behavior. We will further prioritize this to find a fix or a workaround and update the ticket.

**Comment by Venigma** [comment] 2022-12-23 04:26
I am having the same issue, when trying to use a custom expression {{steps.trigger.event.id}} from the Notion trigger in the Update_Page action, it says there is an error and will not work unless I choose a specific page ID

**Comment by lcaresia** [comment] 2022-12-26 12:20
In this case we don't have support to list async options with a dinamic value from other step.

How can we see on image below we don't get the value stored on `{{steps.retrieve_page.$return_value.id}}`, and currently don't have a way to do that.

For now the only way is using the direct ID or choosing one options listed on `Page ID` prop.

![image](https://user-images.githubusercontent.com/12402324/209548200-44cb8ec1-190f-4323-b691-3145974f62e6.png)


Cc: @dannyroosevelt @DilanAthukorala

**Comment by tomnico76** [comment] 2022-12-27 06:59
Hello,

   thank you for your explanation. It is very unfortunate. Without it I
cannot efficiently sync Todoist task list with Notion. My intention was to
detect when Todoist task was completed and then updated status of task in
Notion database.

   Is there a way to do it directly with Node code? Can I use your function
code as an example?

   Best regards

   Tomas



po 26. 12. 2022 v 13:20 odesílatel Lucas Caresia ***@***.***>
napsal:

**Comment by andrewjschuang** [comment] 2023-01-11 17:09
Depends on #3255.

**Comment by yanivpat** [comment] 2023-01-13 23:19
any updates on this?

**Comment by andrewjschuang** [comment] 2023-02-22 15:03
> any updates on this?

Yes, please take a look at https://github.com/PipedreamHQ/pipedream/issues/3255.
Closing this since it's a duplicate.

**Closed by andrewjschuang** 2023-02-22 15:03 UTC
Labels: bug, triaged, tracked internally, prioritized
