### ISSUE TITLE
Instagram Graph API

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12441] opened 2024-06-15 19:08 UTC
### App
Instagram Graph API
https://developers.facebook.com/docs/instagram-api?locale=es_ES

**Comment by sergio-eliot-rodriguez** [comment] 2024-06-16 17:58
Duplicate of https://github.com/PipedreamHQ/pipedream/issues/445

**Closed by sergio-eliot-rodriguez** 2024-06-16 17:58 UTC
Labels: app, user request
