### ISSUE TITLE
[BUG] Can not delete Datastore

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7236] opened 2023-07-12 08:59 UTC
**Describe the bug**
The datastore is empty and it is not used by any worflows. So, from the UI I click "Delete", then I enter the datastore name and click Delete button. I receive no errors, the dialog with the Delete button is still there and the data store is not deleted
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/cce90008-00e5-46b4-bbb6-197bb8f12df5)

**Expected behavior**
The data store should be deleted

**Additional context**
First reported by a customer here: https://pipedream-users.slack.com/archives/CN1BUB92B/p1689151640415289

**Comment by soyabn09** [comment] 2023-07-27 14:46
I'm also having the same issue, and because in props you only get to see the newest 20 created data stores I really want to delete my unused old ones.

**Comment by soyabn09** [comment] 2023-07-27 14:49
![image](https://github.com/PipedreamHQ/pipedream/assets/45386264/4fa5094a-96d3-46cd-a79e-da3da414734a)

**Comment by dylburger** [comment] 2023-07-31 00:20
Duplicate of #3990, tracking there.

**Closed by dylburger** 2023-07-31 00:20 UTC
Labels: bug, triaged, tracked internally
