### ISSUE TITLE
[BUG] HTTP response not working after a delay

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#4279] opened 2022-09-19 11:30 UTC
**Describe the bug**
When using a HTTP trigger with the `HTTP Response` set to `Return a custom response from your workflow`, the response send at the end of the workflow is not working if a delay block is used in the workflow.

**To Reproduce**
1. Create a workflow with the folling components
    1. Trigger: HTTP request with custom response from workflow
    2. Action 1: Delay 10 seconds
    3. Action 2: Response to HTTP request with `OK`
2. Trigger the workflow by openning the trigger url in the browser

**Expected behavior**
The page should load for 10 seconds and display `OK` when action 2 is reached.

**Current behavior**
The page displays `$.respond() not called for this invocation` when action 1 is reached.

**Comment by Hassan-Abbas-SQA** [comment] 2022-09-19 18:35
@LucBerge i am able to reproduce the issue 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/104946677/191086159-aebce152-9525-4c1d-8b1d-fcdb59f05419.png">

**Comment by dylburger** [comment] 2022-09-25 01:26
@LucBerge This is actually by design, and I updated the docs to clarify. You can't use the native delay feature with `$.respond` because we actually end the original execution of the workflow, suspend the workflow state for the delay period, then invoke a separate instance of the workflow code after the delay.

If you're only waiting a short time, can you run a `setTimeout` instead of delay to pause within the same run?

```javascript
// Pause for 10 seconds
await new Promise(r => setTimeout(r, 10000));

// Respond
$.respond({ status: 200 })
```

**Comment by dylburger** [comment] 2022-10-02 23:29
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.

**Closed by dylburger** 2022-10-02 23:29 UTC
Labels: bug, question, triaged

**Comment by LucBerge** [comment] 2022-10-03 07:47
> @LucBerge This is actually by design, and I updated the docs to clarify.

Nice to know

> You can't use the native delay feature with `$.respond` because we actually end the original execution of the workflow, suspend the workflow state for the delay period, then invoke a separate instance of the workflow code after the delay.
> 
> If you're only waiting a short time, can you run a `setTimeout` instead of delay to pause within the same run?
> 
> ```js
> // Pause for 10 seconds
> await new Promise(r => setTimeout(r, 10000));
> 
> // Respond
> $.respond({ status: 200 })
> ```

Working 😄 thanks
