### ISSUE TITLE
[BUG] Github - Create a Pull Request async options fails to load

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#3502] opened 2022-07-22 10:53 UTC
**Describe the bug**

Any Github source using async options to populate props is infinitely loading when attempting to search:

https://share.descript.com/view/NGTVLNu161n

## Reproduction steps

1. Create a new workflow
2. Create a Github New Pull Request (Instant) trigger
3. Connect your Github account
4. Attempt to search in the Repository prop
5. See infinite load

**Expected behavior**
I expect async options to work properly.

## Additional context

1. This issue seems to be happening with Bitbucket as well, not sure if it's an underlying system or devops problem.

2. The code for this New Pull Request (Instant) source is missing from the `github` component in the registry it seems.

**Comment by vellames-turing** [comment] 2022-07-22 14:40
@ctrlaltdylan It's working correctly for me. Is this happening just with one user, or are there more reports about it?

**Comment by ctrlaltdylan** [comment] 2022-07-22 15:08
@vellames-turing a teams customer and myself have experienced the bug. The initial loading of options works, but searching seems to be broken.

**Comment by ctrlaltdylan** [comment] 2022-07-22 15:09
@vellames-turing a teams customer and myself have experienced the bug. The initial loading of options works, but searching seems to be broken.

**Comment by vellames-turing** [comment] 2022-07-22 15:10
Oh, got it! I was able to reproduce it now, tks!

**Comment by vunguyenhung** [comment] 2022-08-03 14:38
Hello there @vellames-turing, as this is pending in TODO for a while, do you have bandwidth to work on this now? Also, could you take a look at [the issue Pierce mentioned](https://github.com/PipedreamHQ/pipedream/issues/3502#issuecomment-1196788460)?

**Comment by vellames-turing** [comment] 2022-08-03 14:49
Hey, yeah, I will jump on it today

**Comment by vellames-turing** [comment] 2022-08-03 17:42
Need some clarification to move ahead. I am not able find the code related to this source. I just pinged @dylburger asking some help :)

**Comment by dylburger** [comment] 2022-08-03 18:40
I'll bring this up with the team during our triage process and we'll investigate. Feel free to move on to the next task @vellames-turing .

**Comment by malexanderlim** [comment] 2023-10-27 21:36
Closing this issue as I'm not able to replicate, looks like this one was fixed!

**Closed by malexanderlim** 2023-10-27 21:36 UTC
Labels: bug, action, blocked, triaged, tracked internally
