### ISSUE TITLE
[ACTION] Aircall - Create & Update Contact

### ISSUE THREAD

**Issue by cbuxton71** [PipedreamHQ/pipedream#7948] opened 2023-09-07 18:51 UTC
**Is there a specific app this action is for?**
Aircall - Create Contact & Update Contact

**Please provide a link to the relevant API docs for the specific service / operation.**
- https://developer.aircall.io/api-references/#create-a-contact
- https://developer.aircall.io/api-references/#update-a-contact

**Comment by adarshjhaa100** [comment] 2023-09-08 20:34
Okay, So what if we create a separate function for monitoring the google sheets. Whenever there's any change, addition, deletion of the contacts, It would call one of the following APIs from aircall:
Create : POST /v1/contacts (https://developer.aircall.io/api-references/#create-a-contact)
Update: POST /v1/contacts/:id (https://developer.aircall.io/api-references/#update-a-contact)
Delete: DELETE /v1/contacts/:id (https://developer.aircall.io/api-references/#delete-a-contact)

In case of modification or deletion for a specific contact, we can fetch the details using: 
https://developer.aircall.io/api-references/#search-contacts, make the required changes and update accordingly.

One question, can this be confirmed that aircall related functionality is present in this component ?( https://github.com/PipedreamHQ/pipedream/tree/master/components/aircall)

**Comment by cbuxton71** [comment] 2023-09-11 18:08
When the Google Sheet is updated, how will the process know which AirCall user needs to have their contacts updated?

I'm not sure how to answer your question about the related functionality being present in the component.

**Comment by GTFalcao** [comment] 2024-01-20 04:38
I followed the documentation to create the actions, but was unable to validate the functionality due to not being able to log into the platform - I created an account and received an email confirming it was activated, but am not able to log into the account.

Moving it forward for the time being, since this was user-requested.

**Comment by malexanderlim** [comment] 2024-01-23 18:25
Hi @vunguyenhung , I've reached out to the Aircall team for an account and will follow up once I hear back. If we don't hear back in the next few days, I'm open to shipping it, and perhaps @cbuxton71 could validate functionality as the requester.

**Comment by malexanderlim** [comment] 2024-01-23 21:07
Hi @vunguyenhung , I've successfully created a test account and shared the credentials - let me know if you're having any issues.

**Comment by GTFalcao** [comment] 2024-01-26 18:55
The issue here was the action hitting the wrong endpoint (create instead of update) - fixed.

**Closed** 2024-01-29 17:13 UTC
Labels: enhancement, help wanted, good first issue, trigger / source, triaged
