### ISSUE TITLE
[BUG] User can not copy the Data Store field value when the value is overflowed

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#7415] opened 2023-07-28 09:08 UTC
**Describe the bug**
User can not copy the Data Store field value when the value is overflowed
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/2acecfac-0e17-4942-8dc5-7444cfe57476)

**Expected behavior**
The long string should be wrapped, or they should be truncated and having the `See more` button that allow user to see the whole content of the string

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome 
 - Version 115.0.5790.110

**Additional context**
Reported by a user here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1690534693598219

**Comment by dylburger** [comment] 2023-10-22 00:19
Thanks for reporting Leo. I'm cleaning up issues and this is a duplicate of #6941

**Closed by dylburger** 2023-10-22 00:19 UTC
Labels: bug, triaged, tracked internally
